### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by chipitsine** [gluck/il-repack#107]
subfolder "cecil" is empty.
so, neither VS solution build, nor gradle works:

18:00:48.681 [INFO] [org.gradle.api.Task] Parsing file ILRepack.sln ...
18:00:50.673 [ERROR] [org.gradle.api.Task] Error during project file parsing: The project file "cecil\Mono.Cecil.csproj"
 was not found.

please, either add files to "cecil" subfolder, or provide a guide where to pick them

**Comment by gluck** [comment]
It's a GIT submodule.
You need to clone using --recursive, *or* use `git submodule init` && `git submodule update` after you clone the repo.
