### ISSUE TITLE
build fails on windows 2012r2 / .net 4.5.2

### ISSUE THREAD

**Issue by chipitsine** [gluck/il-repack#109]
PS C:\ilia\il-repack> .\gradlew.bat msbuild
:nugetRestore UP-TO-DATE
:msbuild
  Mono.Cecil -> C:\ilia\il-repack\cecil\bin\net_3_5_Release\Mono.Cecil.dll
  Mono.Cecil.Mdb -> C:\ilia\il-repack\cecil\bin\net_3_5_Release\Mono.Cecil.Mdb.dll
  Mono.Cecil.Pdb -> C:\ilia\il-repack\cecil\bin\net_3_5_Release\Mono.Cecil.Pdb.dll
ILRepack.cs(45,58): error CS1002: ; expected [C:\ilia\il-repack\ILRepack\ILRepack.csproj]
ILRepack.cs(45,96): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\ilia\il-repack
\ILRepack\ILRepack.csproj]
ILRepack.cs(46,59): error CS1002: ; expected [C:\ilia\il-repack\ILRepack\ILRepack.csproj]
ILRepack.cs(46,98): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\ilia\il-repack
\ILRepack\ILRepack.csproj]
ILRepack.cs(55,39): error CS1002: ; expected [C:\ilia\il-repack\ILRepack\ILRepack.csproj]
ILRepack.cs(55,52): error CS1519: Invalid token '=>' in class, struct, or interface member declaration [C:\ilia\il-repac
k\ILRepack\ILRepack.csproj]
ILRepack.cs(55,67): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\ilia\il-repack
\ILRepack\ILRepack.csproj]
ILRepack.cs(56,40): error CS1002: ; expected [C:\ilia\il-repack\ILRepack\ILRepack.csproj]
ILRepack.cs(56,58): error CS1519: Invalid token '=>' in class, struct, or interface member declaration [C:\ilia\il-repac
k\ILRepack\ILRepack.csproj]
ILRepack.cs(56,78): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\ilia\il-repack
\ILRepack\ILRepack.csproj]

**Comment by timotei** [comment]
Starting from v2.0 (master version now), ILRepack uses C# 6 features, thus it requires .NET 4.6 SDK for compilation (more specifically, msbuild 14). 

You can download 4.6 RC from here: https://msdn.microsoft.com/en-us/library/5a4x27ek%28v=vs.110%29.aspx

**Comment by chipitsine** [comment]
if so, can you please change ToolsVersion="4.0"  --> ToolsVersion="14.0" in ILRepack.csproj ?
it will give people some clue

**Comment by gluck** [comment]
done in https://github.com/gluck/il-repack/commit/3ac91190e12a08e027fc3a7b545fb047f5d14c8f

Thx
