### ISSUE TITLE
ILRepack 2.0 doesn't work on Paket 

### ISSUE THREAD

**Issue by forki** [gluck/il-repack#112]
I tried to upgrade ILRepack in Paket (see https://github.com/fsprojects/Paket/pull/863) but it doesn't work anymore:

![image](https://cloud.githubusercontent.com/assets/57396/8035963/a1035ab8-0df4-11e5-9387-1c233cb9d85f.png)

It says:

    ArgumentException: The argument has to be between 0 and 3.

you can reproduce by running `build Nuget` on that branch.

**Comment by gluck** [comment]
Seems to be linked to this cecil change https://github.com/jbevain/cecil/commit/c123c7bbc63534d90039d5a4748e4826efef6f5c#diff-58c90aaad4e31e5b2a955898cb4ecaabL150

@jbevain any reason for the change from `ToString()` to `ToString(4)` ? the later is failing when major or build no is -1 (no clue when that appends).

Thx

**Comment by jbevain** [comment]
@gluck Version.ToString depends on the number of fields specified at construction time. So `new Version(2,0)` will print `"2.0"`. We want to make sure we get `"2.0.0.0"` in that case.

I'd love to get a repro or a binary with the -1 version.

**Comment by gluck** [comment]
Cf PR https://github.com/jbevain/cecil/pull/227 with the current code, `new ANR("Foo", new Version(2, 0)).FullName` throws an exception, so you're not getting what you expect :)

**Comment by gluck** [comment]
Let me know how eager you are to get a patch on this :)
It "only" happens when you provide a 2 or 3 digit version on ILRepack command line.
Note that if you don't provide the version, it's inherited from the first assembly provided on the cmd line, I had the impression that it'd work in your case (as paket.exe must already have the correct version ?).

Thx !

**Comment by forki** [comment]
yes paket.exe has the right version.

I don't really need to upgrade right now, but I just wanted to help beta-testing ;-)

**Comment by gluck** [comment]
I thought that was your intention, in which case you can further beta-test by removing the `/ver:%s ` argument to your command line :)

**Comment by forki** [comment]
it now seems to work fine. thx

**Comment by forki** [comment]
We might have a new issue with the automatic version detection in paket. Is this fix released?

**Comment by forki** [comment]
https://twitter.com/adamchester/status/609627323424333824

**Comment by gluck** [comment]
Not yet but I'll probably release today or tomorrow

**Comment by gluck** [comment]
And released !

**Comment by forki** [comment]
Awesome. Thanks a lot.
