### ISSUE TITLE
ILRepack doesn't internalize dependencies

### ISSUE THREAD

**Issue by forki** [gluck/il-repack#129]
![image](https://cloud.githubusercontent.com/assets/57396/10255285/a2377116-6949-11e5-9352-c1752fd188fb.png)

Is this intended?

**Comment by gluck** [comment]
Absolutely not, my release process may have an issue, thanks for the heads up, I'll unlist the version till I sort this out!

**Comment by gluck** [comment]
2.0.7 is out, the nuget pkg deps are back to their (non existent) original state, thanks !
