### ISSUE TITLE
ILRepack fails after update from 2.0.5 to 2.0.7

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [gluck/il-repack#130]
After update to 2.0.7 ILRepack.Lib fails with exception FileNotFoundException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral. PublicKeyToken=0738eb9f132ed768'. I try to solve this problem - I have installed Mono.Posix from Nuget. And after this happened another exception: "System.MissingMethodException: Method not found:'Mono.Cecil.PE.ResourceDirectory Mono.Cecil.ModuleDefinition.get_Win32ResourceDirectory()'. 

On 2.0.5 version all works perfect.

**Comment by gluck** [comment]
That's definitely going to be known the worse release ever :fire: 
I'm going to unlist it till the build gets fixed, thanks for the notice !
