### ISSUE TITLE
Lot of failing tests in forked Mono.Cecil

### ISSUE THREAD

**Issue by xen2** [gluck/il-repack#131]
Noticed lot of failing tests in Mono.Cecil, esp. the ones like ImportComplexGenericMethodSpec().

This seems due to the caching system (esp. ImportGenericContext.MethodParameter => FullName comparison fails a lot: sometimes one contains generic arguments and the other one not, or it contains + instead of /).

That makes this Mono.Cecil unusable (we were sharing it)

**Comment by xen2** [comment]
Note: Tried to fix all of them. Available here:
https://github.com/SiliconStudio/Mono.Cecil

**Comment by KirillOsenkov** [comment]
We are using the latest Cecil now.
