### ISSUE TITLE
Types with comma symbol in their names cause to merge bugs

### ISSUE THREAD

**Issue by deniszykov** [gluck/il-repack#135]
Types with comma symbol in their names creates broken references in merged assemblies. 
For example [IteratorStateMachine] generates state-machine class with comma in name
http://take.ms/F7c5L (il-spy failed to properly display this attribute)
which lead to following buggy reference in output file.
http://take.ms/O0XLE

**Comment by gluck** [comment]
Would you happen to have a repro assembly available ?

Thx

**Comment by deniszykov** [comment]
Code:
```c#
	public class MyIterable : IEnumerable<KeyValuePair<ConsoleColor, Action>>
	{
		IEnumerator<KeyValuePair<ConsoleColor, Action>> IEnumerable<KeyValuePair<ConsoleColor, Action>>.GetEnumerator()
		{
			var myState = 1;
			yield return new KeyValuePair<ConsoleColor, Action>();
			myState = 2;
			yield return new KeyValuePair<ConsoleColor, Action>((ConsoleColor)myState, null);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			throw new NotImplementedException();
		}
	}
```
And compiled assembly:
https://onedrive.live.com/redir?resid=2D95F333737CD690!31054&authkey=!AKJgsjkUABOXwxk&ithint=file%2cexe

I researched this a little error and I think it manifests itself only in custom attributes with type references.

**Comment by gluck** [comment]
Which version of ILRepack are you using ? tried right now and the inner type isn't messed with.

**Comment by deniszykov** [comment]
I tested my old repro, and it's doesn't work, sorry :cry: 
So I attaching my assembly which gives this bug.

ILRepack version 2.0.5, C# 6 compiller
ILRepack Command Line: ILRepack.exe /target:exe "/targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319" /xmldocs /union /parallel /internalize "/out:.\out.exe" .\Pluto.exe .\MonoLinker.exe

Both executables:
https://onedrive.live.com/redir?resid=2D95F333737CD690!31106&authkey=!AGNUX51ve6717uE&ithint=file%2cexe
https://onedrive.live.com/redir?resid=2D95F333737CD690!31107&authkey=!ALLVszc2H4j2RPQ&ithint=file%2cexe

On my PC they gives broken reference http://take.ms/5ZkVu

**Comment by deniszykov** [comment]
Still reproduces on 2.0.13 (on provided assemblies), attributes referencing types with comma in name cause broken references.
![image](https://user-images.githubusercontent.com/10157332/31865918-baf1563c-b77f-11e7-8c10-c9879e7d6635.png)

**Comment by KirillOsenkov** [comment]
Do you know if this is still an issue with the latest version?

**Comment by deniszykov** [comment]
I'm unable to reproduce it on v2.0.25
