### ISSUE TITLE
Possible regression on Windows 10 (and possibly other platforms too)

### ISSUE THREAD

**Issue by xen2** [gluck/il-repack#141]
I have issues since https://github.com/gluck/il-repack/commit/ab4dbba9fd1d3ec9bbaff0236fbcf30b33650bc8#diff-668fa2f6cd943b41007b9447ca9adf96L46 has been removed (FixPlatformVersion was running repack.MergeScope before, but not anymore).

Somehow my Win10 now merged assembly fails (merged assembly just crash on startup before any C# code can execute).
Not sure if it could be specific to my assemblies (I will check if they have anything weird).
My case my not be the typical as the second merged assembly is compiled with Roslyn API, and I merge them in memory and do some IL post processing before saving the Cecil assembly (however it worked fine with this FixPlatformVersion () and not without).

For now I will revert back this specific piece of code in my local branch.

**Comment by xen2** [comment]
Noticed RepackImporter.cs is now the place supposed to call FixPlatformVersion, investigating.

**Comment by gluck** [comment]
Hi, would you have any sample assemblies that'd exhibit the behavior ? (or at least did you notice which AssemblyRef was missing in the output assembly ?)

Merging input assembly references shouldn't be required as they should have been merged already when used (I think, unless an IL merge bug remains, which is very possible).

**Comment by KirillOsenkov** [comment]
Please feel free to reactivate if this is still an issue, and we're going to need the .zip file with the assemblies
