### ISSUE TITLE
Can't merge these two dlls， one is old and one is new, I need your help.

### ISSUE THREAD

**Issue by jinjingcai2014** [gluck/il-repack#142]
I want to merge Ufida.T.PU.UIP.dlls and the Ufida.T.PU.Service.dlls.  like this: one is old, and the other one is new. I want to append the new dll to the old dll. But when I merge, I meet these problems: I don't know how to solve these problems:
"D:\PurchaseExtend>D:\ilrepack.2.0.10\tools\ILRepack.exe /union /copyattrs /out:D
:\PurchaseExtend\temp\Ufida.T.PU.Service.dll  D:\PurchaseExtend\pubref\Ufida.T.P
U.Service.dll   D:\PurchaseExtend\pubref1\Ufida.T.PU.Service.dll
INFO: IL Repack - Version 2.0.10
INFO: Adding assembly for merge: D:\PurchaseExtend\pubref\Ufida.T.PU.Service.dll

INFO: Adding assembly for merge: D:\PurchaseExtend\pubref1\Ufida.T.PU.Service.dl
l
INFO: Processing references
INFO: Processing types
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Processing types
INFO: Processing resources
INFO: Fixing references
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Ufida.T.EAP
.AopBase, Version=12.1.0.0, Culture=neutral, PublicKeyToken=null'
   在 Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, Reader
Parameters parameters)
   在 Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   在 Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   在 ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
   在 ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
   在 ILRepacking.Steps.ReferencesFixStep.Perform()
   在 ILRepacking.ILRepack.Repack()
   在 ILRepacking.Application.Main(String[] args)

D:\PurchaseExtend>D:\ilrepack.2.0.10\tools\ILRepack.exe /union  /copyattrs /out:
D:\PurchaseExtend\temp\Ufida.T.PU.UIP.dll  D:\PurchaseExtend\pubref\Ufida.T.PU.U
IP.dll   D:\PurchaseExtend\pubref1\Ufida.T.PU.UIP.dll
INFO: IL Repack - Version 2.0.10
INFO: Adding assembly for merge: D:\PurchaseExtend\pubref\Ufida.T.PU.UIP.dll
INFO: Adding assembly for merge: D:\PurchaseExtend\pubref1\Ufida.T.PU.UIP.dll
INFO: Processing references
INFO: Processing types
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Processing types
INFO: Processing resources
INFO: Fixing references
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'AjaxPro.2,
Version=7.7.31.1, Culture=neutral, PublicKeyToken=null'
   在 Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, Reader
Parameters parameters)
   在 Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   在 Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   在 ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
   在 ILRepacking.ReferenceFixator.FixReferences(MethodDefinition meth)
   在 ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
   在 ILRepacking.Steps.ReferencesFixStep.Perform()
   在 ILRepacking.ILRepack.Repack()
   在 ILRepacking.Application.Main(String[] args)"
I need your help ! Thank you !

**Comment by gluck** [comment]
Hi,

you need to provide the path to the referenced assemblies: `/lib:D:\SomeFolder` (in your case needs to be the folder containing `Ufida.T.EAP.AopBase.dll` or `AjaxPro.2.dll`)

**Comment by jinjingcai2014** [comment]
Thank you very much ! I  will try it .
