### ISSUE TITLE
Support for /allowDup without specifying a type to allow duplicates of all types

### ISSUE THREAD

**Issue by icnocop** [gluck/il-repack#144]
Support for /allowDup without specifying a type to allow duplicates of all types.

ilmerge already has this behavior.

Thank you.

**Comment by gluck** [comment]
May I ask what you use it for ? ILRepack already supports duplicate types by default (renaming later ones) if possible (type is internal/private, or /internalize is provided).

**Comment by Arithmomaniac** [comment]
Someone might use it because they are porting someone else's code from ILMerge and don't want to dig out all the public types.

**Comment by icnocop** [comment]
Sorry I'm replying to your question late.
If there are a lot of duplicate types it's less maintenance than having to specify them explicitly and/or manage them if/when they change.

**Comment by KirillOsenkov** [comment]
This is now supported.
