### ISSUE TITLE
Can't merge assembly with WP8.1 application 

### ISSUE THREAD

**Issue by karanchevsky** [gluck/il-repack#145]
I'm trying to merge an assembly into a windows phone 8.1 application (after unpacking it...) but get the following error: 

INFO: IL Repack - Version 2.0.10
INFO: Adding assembly for merge: InstrumentationTarget.exe
INFO: Adding assembly for merge: InstrumentationLib.dll
INFO: Processing references
INFO: Processing types
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Processing types
INFO: Processing resources
INFO: Fixing references
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
   at ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
   at ILRepacking.Steps.ReferencesFixStep.Perform()
   at ILRepacking.ILRepack.Repack()
   at ILRepacking.Application.Main(String[] args)

Adding [/lib:"C:\Program Files (x86)\Windows Phone Kits\8.1\References\CommonConfiguration\Neutral\Windows.winmd"] as an argument doesn't resolve the issue,
Please help !
Thanks :)

**Comment by timotei** [comment]
I don't think we properly support winmd assemblies, which are very different than a normal one.

Also, what's the actual usage? I don't see how ILRepack would be required/useful in a WP app, since you will package a single app anyway.

**Comment by karanchevsky** [comment]
I want to merge types from my assembly into a 3rd party application, 
later using Mono.Cecil to call methods from my assembly when the application starts

**Comment by gluck** [comment]
Not familiar about WP 8.1 enough to comment about the use case (although it doesn't seem to me you can use Mono.Cecil to _call_ methods).
But if you can dump the dlls you're trying to merge somewhere, I can have a look. AFAICT winmd files are regular dlls stripped of an method impl (so they should work fine as references at least), there's even a fork of ILRepack used to generate those out of regular dlls.

Thx
