### ISSUE TITLE
UWP: System.IO.FileNotFoundException after Merging Universal Windows Assemblies

### ISSUE THREAD

**Issue by sigristb** [gluck/il-repack#150]
I am trying to merge an UWP application with a UWP class library. Merging itself works without an error, but the resulting application immediately crashes at startup with the following exception:

```
System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Additional information: Could not load file or assembly 'Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

Any ideas why it would not find the reference after merging? I found some posts of the same exception together with outputs mentioning Mono.Cecil in the unity forum, so could it just be a problem with the cecil version being used in ilrepack?

Thanks!

**Comment by gluck** [comment]
I'm not really familiar with UWP.

But I know IL, if you can provide the assemblies you're trying to merge ?
(or any assembly which reproduces the error, can be an empty project)

(ILRepack version and command-line used would help as well)

**Comment by sigristb** [comment]
Thank you for the quick response. 

You find a TestProject in Project and the output files in Files in the following attachment:
[IlrepackTestProject.gz](https://github.com/gluck/il-repack/files/160409/IlrepackTestProject.gz)
(For some reason GitHub did not allow me to upload a .zip file, you might have to rename it to .zip before unpacking.)

I created a post build event and the command line is:

```
..\..\..\..\..\tools\ilrepack.exe /out:SomeProgram.merged.exe SomeProgram.exe SomeLibrary.dll
move SomeProgram.exe SomeProgram.old.exe
move SomeProgram.pdb SomeProgram.old.pdb
move SomeProgram.merged.exe SomeProgram.exe
move SomeProgram.merged.pdb SomeProgram.pdb
```

ilrepack version is the latest, meaning 2.0.10. If you want to run the project, just open it on any Windows 10 machine, activate developer mode and run the Debug/x86 config.

**Comment by sigristb** [comment]
I had a look at the assemblies with ildasm myself, and I assume this is the problem:

Original/Input Assembly:
> .assembly extern **windowsruntime** Windows.Foundation.UniversalApiContract
> {
>   .ver 2:0:0:0
> }

ilrepack output Assembly:
> .assembly extern Windows.Foundation.UniversalApiContract
> {
>   .ver 2:0:0:0
> }

I assume, that if the windowsruntime attribute were set in the output assembly, everything would work ok...

**Comment by gluck** [comment]
Fixed in master, PR done to cecil to keep in sync, feel free to give a try before the release.

Thx !
