### ISSUE TITLE
Unable to merge xamarin application.

### ISSUE THREAD

**Issue by zakjut** [gluck/il-repack#151]
I apologize if I am doing something silly, this is the first time I am trying to use a tool like ILRepack or ILMerge. I have created a service "app" with xamarin in vs2015 that I am going to use in several other applications. The issue is that this service app contains references to two external libraries. Since I want to have a single point of contact for my other apps using this service I figured I might be able to merge these libs into my own. I am using the ILRepack version found n NuGet and the following post build command.

    if $(ConfigurationName) == Release (
        cd "$(TargetDir)"
        ren "$(TargetName).dll" "$(TargetName).premerge.dll"
        "$(SolutionDir)\packages\ILRepack.2.0.10\tools\ILRepack.exe" /verbose /internalize /out:"$(TargetFileName)" "$(TargetName).premerge.dll" "a.dll" "b.dll"
    )

However, the build fails with the following error: 

    Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
    1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
    1>     at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
    1>     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
    1>     at Mono.Cecil.TypeReference.Resolve()
    1>     at ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
    1>     at ILRepacking.ReferenceFixator.FixReferences(MethodDefinition meth)
    1>     at ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
    1>     at ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
    1>     at ILRepacking.Steps.ReferencesFixStep.Perform()
    1>     at ILRepacking.ILRepack.Repack()
    1>     at ILRepacking.Application.Main(String[] args)

Before spending more hours trying to tear my hair at this I figured I might ask if ILRepack even works for xamarin applications first?

**Comment by gluck** [comment]
Cant really tell if merging a Xamarin app will be ok, never done one myself.
But ILRepack operates at IL level, so it mostly works fine with anything but nasty (non-plain-string) reflection.

Regarding your error, you nee to provide hint paths where ILRepack can find referenced libraries, when they aren't in the current folder, you can do that using `/lib:PATH_TO_FOLDER`

Happy repacking !

**Comment by zakjut** [comment]
Ahh, I set the copy local field to yes for the Mono.Android reference so it is present in the current folder and now the repacking proceeds as it should. Thanks!

**Comment by zakjut** [comment]
Hmm, I am unable to use the repacked .dll however.

When including it in a project and starting the service contained within, a bunch of classes tries to use the .dlls that I repacked into the main .dll. Leading to a bunch of "package does not exist" errors.

The service works as it should before repacking but when trying to use the repacked file from another application it is unable to actually use the .dlls contained within. Is there some special convention I need to follow when using referenced libraries that are later repacked?

**Comment by gluck** [comment]
Your repacked dll should no longer have any reference to the merged ones, you can inspect assembly references with ILSpy for instance, do you see a/b under _References_ ?

**Comment by zakjut** [comment]
You are of course entirely correct. I used ILSpy to check the repacked .dll and the references are gone, replaced with the actual classes from the referenced libraries instead. It turned out to be a regular VS2015 issue as when I restarted the IDE everything worked as it should.

Thank you once again for the quick replies!
