### ISSUE TITLE
Windows Defender false positive

### ISSUE THREAD

**Issue by JustArchi** [gluck/il-repack#152]
Downloading ILRepack from **[here](http://nuget.org/api/v2/package/ILRepack)** results in false positive from up-to-date Windows Defender: Trojan:Win32/Fethar.B!cl

**Moreover, binaries repacked using ILRepack are falsely flagged as well**.

Clean on VirusTotal: https://www.virustotal.com/file/a3a67cee031404fff22387ccc07d17e32370df18eecdf517db765fc5aad8680e/analysis/1458664979/

![image](https://cloud.githubusercontent.com/assets/1069029/13959693/6ca0ca6e-f055-11e5-9899-ff5aa49aac67.png)

Would be really cool if you could do something with it :cry:

**Comment by gluck** [comment]
oh boy, just what can I do with that :'(
Any idea how to find the pattern Windows Defender is looking for ?

**Comment by JustArchi** [comment]
No clue :cry: 

I tried to report my ASF binaries **[here](https://www.microsoft.com/security/portal/submission/submit.aspx)** as "I believe this file should not be detected as malware", but file is either not detected as malware, or promised to be "fixed" with next signature updates, yet nothing happens. I sent e-mail to support center in the meantime (without getting response yet), and today I found totally accidentally the (very likely) reason of why that is happening.

Try it yourself, perhaps you'll have more like with reporting ILRepack as non-malware than me. I'm afraid I can't help you any more than that :cry:

**Comment by lextm** [comment]
@JustArchi you should report to Microsoft as a developer,

https://www.microsoft.com/security/portal/mmpc/developer/resources.aspx

**Comment by JustArchi** [comment]
It's still not my binary which is causing the problem, but ILRepack, so I believe @gluck should do that, as I'm not even authorized to do so.

**Comment by gluck** [comment]
I didn't manage to reproduce that, Windows Defender doesn't seem to complain on my side ... Will see if others report it.

**Comment by JustArchi** [comment]
Not false positive anymore as of today's update. Let's hope it doesn't come back :+1:

**Comment by gluck** [comment]
:sweat_smile:

**Comment by lcornejo** [comment]
Unfortunately it came back. I did select the option for doing the update on exit.

![trojan](https://cloud.githubusercontent.com/assets/436134/16085558/09b1875c-32e2-11e6-9d82-904336bc6d05.PNG)
![trojan2](https://cloud.githubusercontent.com/assets/436134/16085559/09b68be4-32e2-11e6-829f-4fc116b73497.PNG)

**Comment by JustArchi** [comment]
Confirmed :cry:

**Comment by JustArchi** [comment]
Closed in favour of https://github.com/gluck/il-repack/issues/218
