### ISSUE TITLE
Crash while packing Microsoft.AspNetCore.Mvc.Razor.dll

### ISSUE THREAD

**Issue by PhilipDaniels** [gluck/il-repack#160]
Would appreciate some assistance with this one. Given the number of dependencies in these new-fangled NetCore projects some sort of merging is required :-)

**TL;DR**
`
ERROR: Failed to load assembly C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Razor.dll
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Razor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
`

## Steps to reproduce
Create a new console app (at least 4.5.1.) called Server1

    Install-Package Microphone.AspNet
    Install-Package ILRepack

[Microphone on NuGet](https://www.nuget.org/packages/Microphone.AspNet/)

Create a folder to hold the output called "packout" and then run following powershell script from root directory after compiling the solution:

    $dlls = (Get-ChildItem ./bin/Debug/*.dll)
    ../packages/ILRepack.2.0.10/tools/ILRepack.exe -verbose -out:./packout/Server1.exe ./bin/Debug/Server1.exe $dlls

Error log is as follows:

`INFO: IL Repack - Version 2.0.10
VERBOSE: Runtime: ILRepack, Version=2.0.10.0, Culture=neutral, PublicKeyToken=null
VERBOSE:  - BamlParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
VERBOSE:  - Fasterflect, Version=2.1.3.0, Culture=neutral, PublicKeyToken=38d18473284c1ca7
VERBOSE:  - ILRepack, Version=2.0.10.0, Culture=neutral, PublicKeyToken=null
VERBOSE:  - Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
VERBOSE:  - Mono.Cecil.Mdb, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
VERBOSE:  - Mono.Cecil.Pdb, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
VERBOSE:  - Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
INFO: Adding assembly for merge: ./bin/Debug/Server1.exe
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microphone.AspNet.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microphone.Core.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AI.Agent.Intercept.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AI.DependencyCollector.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AI.PerfCounterCollector.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AI.ServerTelemetryChannel.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.ApplicationInsights.AspNetCore.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.ApplicationInsights.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Antiforgery.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Authorization.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Cors.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Cryptography.Internal.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.DataProtection.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.DataProtection.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Diagnostics.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Hosting.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Hosting.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Html.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Http.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Http.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Http.Extensions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Http.Features.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.HttpOverrides.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.JsonPatch.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Localization.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Abstractions.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.ApiExplorer.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Core.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Cors.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.DataAnnotations.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Formatters.Json.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Localization.dll
INFO: Adding assembly for merge: C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Razor.dll
ERROR: Failed to load assembly C:\temp\Server1\Server1\bin\Debug\Microsoft.AspNetCore.Mvc.Razor.dll
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Razor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArgument(Collection`1& fields, Collection`1& properties)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeNamedArguments(UInt16 count, Collection`1& fields, Collection`1& properties)
   at Mono.Cecil.CustomAttribute.<Resolve>b__34_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
   at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module)
   at Mono.Cecil.ImmediateModuleReader.<ReadModule>b__1_0(ModuleDefinition module, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ILRepacking.ILRepack.ReadInputAssembly(String assembly, Boolean isPrimary)
   at ILRepacking.ILRepack.ReadInputAssemblies()
   at ILRepacking.ILRepack.Repack()
   at ILRepacking.Application.Main(String[] args)
`

**Comment by gluck** [comment]
If the missing lib is in your output folder, try adding /lib:./bin/Debug

(Ideally shouldn't be needed but it is for now)
Le 14 juil. 2016 5:48 PM, "PhilipDaniels" <notifications@github.com> a
écrit :

**Comment by PhilipDaniels** [comment]
Works now! Thanks for the quick response, much appreciated.
