### ISSUE TITLE
2.0.12 and above does not work on Mac OS / Linux due to pdbstr.exe

### ISSUE THREAD

**Issue by undeadcat** [gluck/il-repack#173]
As the subject says, I'm attempting to use ILRepack on Mac OS and Mono and found that versions built after https://github.com/gluck/il-repack/commit/c7cdb36f075a6def965a031401cdfe9e199fc77f don't work because ILRepack attempts to read source server info using pdbstr.exe which is obviously a native Windows executable.

I tried removing the step that deals with source servers, and the resulting version works for me: ILRepack works, and my app, after merging, works as intended.

Making the step run only on Windows seems like an easy fix. 

The question is:
Do you want the fix?
Do you want ILRepack to work on non-Windows OSes but without support for merging source server info?
I couldn't find an explicit statement that support for non-Windows OSes is a goal and realize that my use case working for me could be an unintended accident.

**Comment by timotei** [comment]
This is only my PoV: 

Support for non-Windows OSes is probably not a goal in itself, but something that is nice to have unless it requires sacrificing some important feature. 

See examples in the project: 

* Handling unix OSes in `build.gradle`: https://github.com/gluck/il-repack/blob/master/build.gradle#L58 
* Specifying which tests are Windows only: https://github.com/gluck/il-repack/blob/master/ILRepack.IntegrationTests/WPFScenarios.cs#L9

IMO, a flag to disable pdbstr or by default skip it and print a warning on UNIX OSes should fine. But probably the latter is a more desirable way to do it.

**Comment by gluck** [comment]
As Timotei said, we should try to support UNIX if possible, this breakage in 2.0.12 was an overlook on the review, PR welcome.

Cc @reeflog for thoughts.
