### ISSUE TITLE
Support for merging into existing assembly

### ISSUE THREAD

**Issue by maritaria** [gluck/il-repack#180]
With unity assemblies changing the order of fields on classes breaks the game. I would like to merge into an existing `AssemblyDefinition` instance, in the hopes that the metadata for the original assembly stays the same, and only merge another assembly into it.

I figure something along the lines of setting `ILRepack.TargetAssemblyDefinition` could provide an easy solution

**Comment by timotei** [comment]
Just to confirm, "Unity assemblies" = Unity3d?

Do you have a sample of such breakage? Seems weird as we don't change the order or fields (unless cecil does it)

**Comment by maritaria** [comment]
Yes I ment Unity3D. Issue may have had different cause, you can close the issue. If I find a solid repro i'll comment here again
