### ISSUE TITLE
Mono.Cecil 0.10 support

### ISSUE THREAD

**Issue by manu-st** [gluck/il-repack#182]
Hi,

Just wanted to know what was the status of using Mono.Cecil 0.10 in il-repack. I see there is a 0.10 branch, but it is not clear if it is up-to-date.

Thanks!

**Comment by gluck** [comment]
The branch should be usable, save for debug (PDB/MDB) support, and more recent fixes (if any).
It's stiff missing that part to be merged into master though.

**Comment by xen2** [comment]
What's missing for PDB/MDB exactly? Might look into it.

**Comment by xen2** [comment]
Update: found what needs to be done for PDB/MDB, investigating now.

**Comment by xen2** [comment]
FYI, I have everything working in https://github.com/xen2/il-repack/tree/0.10

It currently needs https://github.com/xen2/cecil/tree/ilrepack (little bit temporary, until things get cleaned up and merged back in master)

Specifically, https://github.com/jbevain/cecil/pull/351 and https://github.com/jbevain/cecil/pull/353 will allow full Native PDB support alongside Portable PDB.

**Comment by xen2** [comment]
Side note: I had weird problem with Baml (it was removing all extra assembly info, including from non merged types.
Fixed in this commit: https://github.com/xen2/il-repack/commit/837337023f427368459a78a75b027c7e52fa4a1c

**Comment by gluck** [comment]
@xen2 your branch looks good, how are the symbols generated ? is it still native PDB or Portable ?

**Comment by xen2** [comment]
It supports both of them.
New cecil added portable PDB and recently reworked and integrated my native PDB branch.

**Comment by SimonCropp** [comment]
@gluck any chance of this being pulled in any time soon?

**Comment by SimonCropp** [comment]
note that there were some upstream cecil pdb fixes recently 
![image](https://cloud.githubusercontent.com/assets/122666/26484051/8af11218-4233-11e7-98c5-e6adbc7a3b53.png)

**Comment by tephe** [comment]
Any change we could integrate cecil 0.10 on master? Looks like 0.10 was released as stable and [0.10.1]( https://github.com/jbevain/cecil/releases) was already released

Thanks

**Comment by caozhiyuan** [comment]
anyone update git submodule? it no work on net core pdb. i will use source code compile

**Comment by MaxXor** [comment]
Any update on this? All bits for portable PDB support are added to Mono.Cecil.

**Comment by KirillOsenkov** [comment]
Our master branch is now using the very latest Cecil.

**Comment by MaxXor** [comment]
Thank you.
