### ISSUE TITLE
ExcludeFile option is awkward use to when using ILRepack.Lib

### ISSUE THREAD

**Issue by mzboray** [gluck/il-repack#185]
I was using ILRepack via the lib package and found that I wanted to use the exclude option, however it is a little tricky to use from there.

This for example will throw a NRE because ExcludeInternalizeMatches is not set:
```
File.WriteAllLines("test.txt", new[] { "one", "two", "three" });
var opts = new RepackOptions()
{
    Internalize = true,
    ExcludeFile = "test.txt"
};
Console.WriteLine(opts.ExcludeInternalizeMatches.Count);
```

Turns out ExcludeFile is set and read in the RepackOptions constructor so the only way to use it is to pass it via command-line style arguments. This works:

```
File.WriteAllLines("test.txt", new[] { "one", "two", "three" });
var opts = new RepackOptions(new[] { "--internalize:test.txt" });
Console.WriteLine(opts.ExcludeInternalizeMatches.Count);
```

Everything works fine for the command line tool, but its a bit of a header scratcher when using it as a library. A better option would be to just allow setting the exclude regexes directly, but the collection is null unless initialized by the ExcludeFile.

**Comment by gluck** [comment]
I agree, usage as lib is awkward.
I'd welcome a PR to improve this (while keeping both backward compatibility, and compatibility with ILMerge options).

Thx.

**Comment by mzboray** [comment]
Ok, why not. The simplest thing to do is at minimum initialize ExcludeInternalizeMatches so that callers can just add to it. Another item would probably be to make setting the ExcludeFile replace the contents of ExcludeInternalizeMatches. With a few doc comments it seems reasonably understandable, if a little quirky. That should maintain the existing command line behavior and options.

If that sounds good, I can probably submit a PR for it sometime tomorrow.

**Comment by gluck** [comment]
LGTM, thanks !
