### ISSUE TITLE
Missing baml resource

### ISSUE THREAD

**Issue by ManniManfred** [gluck/il-repack#189]
I have a winforms exe, that uses an other dll with wpf.
Repacking is successful, but on first access to a xaml an exception occur with message, that the resource "...xaml" is not found.

My current workaround is adding an empty WPF User Control

**Comment by timotei** [comment]
@ManniManfred Which ILRepack version are you using?

**Comment by ManniManfred** [comment]
I test it with 2.0.12.0 and with the current master branch.

**Comment by timotei** [comment]
Do you have a working example of the issue?

**Comment by ManniManfred** [comment]
I create an example to reproduce this issue:
[ILRepackBamlErr.zip](https://github.com/gluck/il-repack/files/1207996/ILRepackBamlErr.zip)

**Comment by ManniManfred** [comment]
@timotei Could you reproduce that with my example?

**Comment by timotei** [comment]
@ManniManfred I was fairly busy these days, will hope to do it next week. Thanks!

**Comment by timotei** [comment]
@ManniManfred FYI, I reproduced the issue, a fix is incoming.

**Comment by timotei** [comment]
@ManniManfred Can you check on your side if this fixes the issue? So that a new version can be released?

**Comment by ManniManfred** [comment]
yes this works. Thank you
