### ISSUE TITLE
Unhandled exception when trying to delete file in SourceServerData.PdbStr.Finalize

### ISSUE THREAD

**Issue by mzboray** [gluck/il-repack#191]
I've been using ILRepack as a library (via ILRepack.Lib) inside an MSBuild task. Occasionally, I see the task fail with the following error:

>Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\mzboray\AppData\Local\Temp\tmp27CB.tmp' because it is be
ing used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at ILRepacking.Steps.SourceServerData.PdbStr.Finalize()

**Comment by gluck** [comment]
As you can guess, that's going to be difficult to troubleshoot 😓 
Maybe highlight the version of ILRepack you get this exception with, and if you get it with commandline only or with VS open.
As this (tmp) file is an executable (pdbstr.exe), might be worth checking if an antivirus is in play.

Good luck

**Comment by mzboray** [comment]
It was on the last release of lib nuget, 2.0.12, I believe.

Actually I am able to repro a similar effect in a test, with `PdbStr`. The following fails for me most of the time when run in Release mode, but never in Debug.

    [TestFixture]
    class PdbStrTest
    {
        private volatile Exception _backgroundException;
        private UnhandledExceptionEventHandler _handler;

        [SetUp]
        public void Before()
        {
            _handler = (o, e) =>
            {
                _backgroundException = (Exception)e.ExceptionObject;
            };
            AppDomain.CurrentDomain.UnhandledException += _handler;
        }

        public void After()
        {
            AppDomain.CurrentDomain.UnhandledException -= _handler;
        }

        [Test]
        public void RunInLoop()
        {
            for (int i = 0; i < 200; i++)
            {
                var pdbStr = new PdbStr();
                var bytes = new byte[65536];
                Assert.IsNull(_backgroundException, "error on iteration: {0}", i);
            }
        }
    }

Note that NUnit 2.6.4 by default hides these background exceptions, hence all the boilerplate with the appdomain unhandledexception notification.

Looking a little more at how this is used, I believe what happening is that in release mode the JIT determines that the `PdbStr` instance allocated by `SourceServerDataRepackStep` is not used after a certain point, but code inside Write (mostly likely, but I suppose it could be Perform) is still running, using the temp file that had been allocated. The GC cleans up and the finalizer runs causing the IOException while the main thread is still using the file. In Debug mode, none of this happens because methods are not inlined and locals are typically kept alive much longer.

I believe the proper fix would be to do more deterministic clean up of PdbStr, perhaps making it IDisposable. The `SourceServerDataRepackStep` would probably then need dispose of this or itself be disposable so the main workflow can cleanup at the end. Also the finalizer could just catch if it fails, since this is only a temp file that the OS can clean up later.

**Comment by gluck** [comment]
That seems correct as per [this blog post](https://blogs.msdn.microsoft.com/cbrumme/2003/04/19/lifetime-gc-keepalive-handle-recycling/)

👍

**Comment by mzboray** [comment]
Sorry I didn't get back to this right away. I thought I could work around it by doing a GC.KeepAlive on the ILRepack object in my code. That made the problem less prevalent but still leads to the occasional crash. That PR should fix it.
