### ISSUE TITLE
ILRepack Not Renaming Duplicate Types

### ISSUE THREAD

**Issue by thefringeninja** [gluck/il-repack#193]
Trying to merge IdentityServer3 and its WsFed plugin (version 2.6):

`ILRepack.exe -internalize -wildcards -union -out:./merged/IdentityServer3.dll IdentityServer3.dll IdentityServer3.WsFederation.dll`

And then loading the assembly gives me

> Unhandled Exception: System.BadImageFormatException: Duplicate type with name 'System.Web.Http.Properties.System.Web.Http.CommonWebApiResources'

I've tried various combinations of `allowDup` and `union` with no effect.

In fact, this type appears duplicated in several namespaces. The only two things I can think of are 1) These types have a `[CompilerGenerated]` on them or 2) These assemblies have already [ILMerged](https://github.com/IdentityServer/IdentityServer3/blob/master/default.ps1#L73) their dependencies into them.

**Comment by KirillOsenkov** [comment]
There is `/renameinternalized`, it just needs to be documented.
