### ISSUE TITLE
Support for portable PDBs

### ISSUE THREAD

**Issue by jnm2** [gluck/il-repack#197]
With the new csproj format, the default is the superior portable PDB format for all .NET projects, including traditional .NET Framework apps.

This is somewhat of a integral issue. Where should this capability be on the roadmap?

**Comment by lextm** [comment]
Duplicate of #182

**Comment by van800** [comment]
On mac/linux only ppdb can be used.

**Comment by jnm2** [comment]
Closing as duplicate of #182.
