### ISSUE TITLE
Strange issue when attempting to merge Microsoft.Practices.Unity.dll

### ISSUE THREAD

**Issue by Shaamaan** [gluck/il-repack#199]
I'm not sure how to debug this, and I apologize in advance for the very generic issue report - I simply don't have any more information at this time. I will provide all that I know.

I use ILmerge to package my DLLs along with some external libraries into a single package for use with Microsoft Dynamics CRM. ILmerge, however, is slow and can sometimes hang up.

I've tried using ILrepack - this works... until I add the external DLL "Microsoft.Practices.Unity.DLL". Actually, this isn't entirely true - ILrepack will create a package correctly, but said package will no longer work with MS CRM. Unfortunately, CRM only throws a generic "Unable to load plug-in assembly" error with nothing else to go on.

All I know is this:
- if I replace ILrepack with ILmerge (and keep the rest of the merge command the same), then the merged DLL will work
- if I use ILrepack and remove the "Microsoft.Practices.Unity.DLL" from the merge command, the DLL will work and CRM will accept it but will fail at runtime when it can't find Unity

I don't really know what else I can do to try and resolve the problem. Currently, I've gone back to using ILmerge, but I'd love to switch to ILrepack as it's a lot faster.

**Comment by gluck** [comment]
Too many things can go wrong with repacking to help you here.
You could try to debug (attach) to the CRM app and catch the exception while loading the plugin to get more details out of it. Alternatively the exception details may be in the EventManager (sometimes does).

Sorry for the late (and clueless) reply.
