### ISSUE TITLE
Build task for repack

### ISSUE THREAD

**Issue by leotsarev** [gluck/il-repack#202]
There is MSBuild task for ILRepack, but it contains outdated version of ILRepack.
https://github.com/peters/ILRepack.MSBuild.Task
Do you consider have task like that as part of your project and your NuGet ?

**Comment by gluck** [comment]
Definitely, likely more in the approach of the PR #196 
It was abandonned because its author no longer needed it / ILRepack, but it looks like a neat approach, waiting for someone to pick it up :)

**Comment by KirillOsenkov** [comment]
There are a bunch of these now:
https://www.nuget.org/packages?q=ilrepack

https://www.nuget.org/packages/ILRepack.Lib.MSBuild.Task seems to be the most "official".

There's also:
https://www.nuget.org/packages/ILRepack.FullAuto
