### ISSUE TITLE
Resolving package references

### ISSUE THREAD

**Issue by softlion** [gluck/il-repack#206]
I'm using beta version of ilrepack.  
It is unable to find any package references of a netstandard 2 lib merged with another netstandard 2 lib.  
I manually added this one:  

    /lib:`"~/.nuget/packages/NETStandard.Library/2.0.0/build/netstandard2.0/ref`""

But ilrepack asks the same for all other packages in the project. He is not able to add a star folder as /lib ? Something like would be good:

    /lib:`"~/.nuget/packages/**"

**Comment by emysa341** [comment]
@softlion You can add multiple references to it, I am doing same with cake build. The work around would be to add reference to netstandard2.0/ref, which you already did. In addition, also add references to YourProject/bin/netstandard2.0/. Or may to location where your all dll fles exists. After that merging should work fine once these both references are there
