### ISSUE TITLE
Repack an "addin" dll?

### ISSUE THREAD

**Issue by ManniManfred** [gluck/il-repack#210]
hi, is there a way to repack a "addin" dll?
I have the following scenario:
* lot of base dll's
* one exe that use the base dll's
 this one is repacked in one exe with all base dll's
* one addin dll, that should be dynamically loaded in some cases from a base dll

My problem is now, that the addin is not correctly loaded, because there are missing references.
Is there a possiblity to repack the addin dll against new the repacked exe?

**Comment by gluck** [comment]
Hi,

It depends if your base DLL(s) serve as an API between your exe and addin (e.g. IOC framework), or if they are "utility" libraries, which could be loaded independently (potentially in different versions) by the exe/addin (e.g. JSON parser).

ILRepack is really for the later, as the repack'ed assemblies lose their identity and become part of the repacked one (almost exactly as if you had copied the code in your project).

For the former use case, the API assemblies need to retain their identity, you can't use ILRepack/ILMerge.
Beside keeping the API dlls as separate files, Fody.Costura may also work if applied on the exe (as it retains the assembly identity).

Good luck.
