### ISSUE TITLE
Option to exclude external assembly

### ISSUE THREAD

**Issue by FixRM** [gluck/il-repack#212]
Hi. I'm getting the error "Failed to resolve assembly" during merge. The problem is that I don't need this assembly to be merged as it will be available in target environment.

**Comment by lextm** [comment]
Let ILRepack be able to resolve an assembly (so that Mono Cecil can read the metadata), and that does not mean you need to merge that assembly with others. I think you just misunderstood the concepts.

**Comment by FixRM** [comment]
How can I do this? This assembly is available in the same folder as my. What should I do to let ILRepack to be able to resolve it?

p.s. ILMerge is ok with that so I consider this is an ILRepack issue/feature

**Comment by deniszykov** [comment]
if it is .NET Framework assembly you could specify path to Framework's location ```"/targetplatform:v4,<PATHTOFRAMEWORK>"```

**Comment by FixRM** [comment]
No it is part of MS Dynamics 365 SDK. The problem is that target system use reflection to create instance of my classes, so they must be extended from external type which is part of SDK assembly

**Comment by gluck** [comment]
You may need to specify `/lib:<FOLDER_INCLUDING_THE_ASSEMBLY>`.
I didn't think it was required if the assembly was in the same folder of one of the assemblies you're trying to merge, but give it a try already.

**Comment by FixRM** [comment]
It looks like it work. Error has gone and I don't see SDK assembly classes using reflector. May I suggest it is still a bug?

**Comment by gluck** [comment]
It looks like it has never been the case, it could be implemented though.
cf https://github.com/gluck/il-repack/blob/3829e3db36ffbf511fcec05316bbf36b33ce83fb/ILRepack/ILRepack.cs#L391

**Comment by honzakostejn** [comment]
Hello there! 
I have the same issue. We are developing Model-driven apps on Microsoft PowerPlatform (re-branded dynamics). We were using ILMerge and it worked just fine, until we switched to the new .csproj structure.
Can someone help me out?

I'm using ILRepack 2.0.16. I'm referencing a few projects and two other nugget packages:
![image](https://user-images.githubusercontent.com/32060653/50845996-6e567180-136e-11e9-90f0-447cdb6cba23.png)

My .csproj looks like this:
![image](https://user-images.githubusercontent.com/32060653/50846069-8f1ec700-136e-11e9-944d-6a340d229972.png)

With this setup, I'm encountering the same issue:
![image](https://user-images.githubusercontent.com/32060653/50846133-b83f5780-136e-11e9-9c2b-1a8703e1a291.png)

**Based on this thread, I tried this:**
![image](https://user-images.githubusercontent.com/32060653/50846244-ffc5e380-136e-11e9-85ea-191700f85d49.png)

And got this result:
![image](https://user-images.githubusercontent.com/32060653/50846561-c2158a80-136f-11e9-8cb7-4459558efb1d.png)

But I have no luck with this setup. Am I doing something wrong? Thanks for help. <3

**Comment by FixRM** [comment]
Hello @honzakostejn,

I use this tool for the same purpose. I highly recommend you to use this MSBuild taks: https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task. You can see sample config here: https://github.com/FixRM/D365Extensions

**Comment by honzakostejn** [comment]
@FixRM,

thanks a lot! I'll definitely go through your repo.

But I managed to solve my issue today. I just tweaked .csproj a little. It works just fine. I'll write short blogpost and post it here, if someone had the same issue.

**Comment by wh1t3cAt1k** [comment]
@honzakostejn my friend, I need your blog post so desperately...

**Comment by KirillOsenkov** [comment]
The resolver has been improved in the latest version, please try the latest and open a new bug if there's still an ILRepack issue. Thanks.
