### ISSUE TITLE
Conflict Resolution is causing runtime problems

### ISSUE THREAD

**Issue by luk-rs** [gluck/il-repack#216]
Hi guys,

I'm having an issue with the merged version of my application which is causing me runtime problems.

I can see an issue with system.net.http lib as follows, while merging the application:

`Target _HandlePackageFileConflicts:`
   
`Encountered conflict between 'Reference:System.Net.Http' and 'Platform:System.Net.Http.dll'.  Choosing 'Reference:System.Net.Http' because AssemblyVersion '4.1.1.2' is greater than '4.0.0.0'.`
   
`Encountered conflict between 'Platform:System.Net.Http.dll' and 'CopyLocal:C:\Users\santosl\.nuget\packages\system.net.http\4.3.3\lib\net46\System.Net.Http.dll'.  Choosing 'CopyLocal:C:\Users\santosl\.nuget\packages\system.net.http\4.3.3\lib\net46\System.Net.Http.dll' because AssemblyVersion '4.1.1.2' is greater than '4.0.0.0'.`

The extended version of my app is running properly but after the merge, and despite running, i get a runtime error since it is expecting properties that have been deprecated on the target lib from the chosen version to the targeted version.

I was wondering how can i overcome this issue. Maybe there is a way of letting the merge tool know which one to choose.

Other thing that I would like to know is how does the merge tool behave with binding redirects.

Thanks in advance,
Luis

**Comment by KirillOsenkov** [comment]
Hi, it's not clear that there's a bug in ILRepack. If you think ILRepack is at fault, please formulate the problem more a bit more clearly. Thanks!
