### ISSUE TITLE
Is it expected that pdb files are not merged?

### ISSUE THREAD

**Issue by van800** [gluck/il-repack#217]
For a project here 
https://github.com/JetBrains/resharper-unity/tree/master/unity
pdb files were not merged automatically, so I added at least coping pdb of the main assembly.

**Comment by gluck** [comment]
You need to pass `DebugInfo=true` to ILRepack (that is the default when executed through command-line, but not through MSBuild tasks which you seem to be using).

**Comment by van800** [comment]
Thanks!

**Comment by SolidSoils** [comment]
Setting `DebugInfo=true` may not always be the solution. ILRepack cannot process the default pdb output of "new style" projects. To fix this I added these settings to the csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
</Project>
```
