### ISSUE TITLE
virus in nuget package ILRepack 2.0.15?

### ISSUE THREAD

**Issue by van800** [gluck/il-repack#218]
![image](https://user-images.githubusercontent.com/1482681/36111882-f672f3e0-1027-11e8-9662-23d974259f85.png)

**Comment by timotei** [comment]
Looks good to me: https://www.virustotal.com/#/file/06cd8770218e4e8be45dfb733bd34bc0675b9f4f0cb6371ed7b9ebbffeca5122/detection

Most likely it's a super aggressive heuristic? I see other issues on other projects like https://github.com/crazy-max/WindowsSpyBlocker/issues/82

**Comment by gluck** [comment]
Are your windows defender signatures up-to-date ? Think we had that issue in the past but they resolved the false detection since (either that or they introduced another one).

**Comment by van800** [comment]
Yes, my windows defender signatures are up-to-date.
