### ISSUE TITLE
Bug: cannot reduce access in 2.0.15

### ISSUE THREAD

**Issue by coderb** [gluck/il-repack#219]
The following code fails when run through ilrepack on windows.  the error is `Unhandled Exception: System.TypeLoadException: Derived method 'Meth' in type 'TestIlRepack.ArrayHandler``1' from assembly 'x, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.`

The method in `Class3` is having its access changed to `internal` from `public` while the base class remains `public`.

```
using System;
using System.Threading.Tasks;

namespace TestIlRepack {
    class Program {
        static void Main(string[] args) {
            GC.KeepAlive(new Class3());
            System.Console.WriteLine("done");
        }
    }

    class Class3 : Class2<Array> {
        public override ValueTask<Array> Meth() { 
            throw new NotImplementedException();
        }
    }

    abstract class Class2<T> : Class1 {

        public abstract ValueTask<T> Meth();

        internal override ValueTask<T2> Meth<T2>() {
            throw new NotImplementedException();
        }
    }

    abstract class Class1 {
        internal abstract ValueTask<T> Meth<T>();
    }
}

```

**Comment by gluck** [comment]
Hi, what command/arguments do you pass to ILRepack ? also which version are you using ?

**Comment by coderb** [comment]
version 2.0.15

no special flags, just input and output file name.

the packed file only fails to run on windows.  mono/linux seems to be tolerant of the access tightening that happens on Class3.

have you tried to reproduce?

**Comment by gluck** [comment]
Thanks.
Not yet tried, but vould be related to the logic [here](https://github.com/gluck/il-repack/blob/master/ILRepack/ReferenceFixator.cs#L102) if you wanna peek.

**Comment by coderb** [comment]
looked at the code, just a guess:
...it doesn't fail if Class1 is removed, so could it be that the "base-most method" logic is confusing the 2 method signatures?

**Comment by skarllot** [comment]
Any action was taken against this issue?

**Comment by Logerfo** [comment]
This is happening to me when packing Npgsql.

**Comment by titomor-outsystems** [comment]
It's happening to me as well in Npgsql (v 4.1.5).

**Comment by titomor-outsystems** [comment]
Do you know of any fork that has fixed this ?

**Comment by knutdrofus** [comment]
I ran into this for Npgsql as well, using ilrepack 2.0.18. I created a small sample project that demonstrates the problem here:  https://github.com/knutdrofus/ilrepack_npgsql_issue

For me, the error appears at runtime, during a type discovery phase during startup, when we're manually feeding types to an IOC container. Not sure if this is a bug or just me using ilrepack incorrectly.

**Comment by MaMazav** [comment]
Also hit this on Program Synthesis: https://www.microsoft.com/en-us/research/publication/program-synthesis/#:~:text=Program%20synthesis%20is%20the%20task,holy%20grail%20of%20Computer%20Science. 

Any plan to merge the fix?

**Comment by idigra** [comment]
Also hit this on Program Synthesis: https://www.microsoft.com/en-us/research/project/prose-framework/.

In that case, it's for protected method that overrides a parent class' method, and later overriden by a deeper child.

Any plan to merge the fix?

**Comment by KirillOsenkov** [comment]
Thank you @coderb and @knutdrofus for providing detailed repros! They were very helpful when investigating this.

I have a fix ready here:
https://github.com/KirillOsenkov/il-repack/commit/a8b6ad2aaf41630e9bc47cbdcdac531f56ffefd0

I've verified that it fixes both npgsql as well as the example at the top of this bug.

**Comment by KirillOsenkov** [comment]
@idigra I also verified that PROSE works fine too.

**Comment by MaMazav** [comment]
> @idigra I also verified that PROSE works fine too.

Great, thanks :) Is an official nuget with the fix planned to be released?

**Comment by KirillOsenkov** [comment]
Yes, stay tuned

**Comment by deniszykov** [comment]
@KirillOsenkov do you plan update Mono.Cecil to latest version?

**Comment by KirillOsenkov** [comment]
Yes, will do a bunch of modernization and go through the outstanding PRs and bugs as time allows

**Comment by KirillOsenkov** [comment]
Try this fix out: https://www.nuget.org/packages/ILRepack/2.0.22
