### ISSUE TITLE
InvalidOperationException using SHA1Managed, violation of FIPS Algorithm Policy

### ISSUE THREAD

**Issue by travis-teitsch** [gluck/il-repack#220]
The call to System.Security.Cryptography.SHA1Managed for signing assemblies is failing FIPS compliance because it is using an algorithm implemented in managed code. 

The method call to System.Security.Cryptography.SHA1Managed from within one of the Mono.Cecil libraries causes an InvalidOperationException when FIPS compliance is enabled on a Windows computer. The method call would have to be changed to either the SHA1CryptoServiceProvider or SHA1Cng implementations for FIPS compliance, but that may be outside of your power (since the code seems to reside somewhere in Mono.Cecil) and maybe not even be desirable.

If you're interested, here's more information on FIPS (jump to section "Information for Software Developers" to read up on FIPS-compliant crypto implementations in .NET): https://technet.microsoft.com/en-us/library/cc750357.aspx

SHA1CryptoServiceProvider: https://msdn.microsoft.com/en-us/library/system.security.cryptography.sha1cryptoserviceprovider(v=vs.110).aspx

SHA1Cng: https://msdn.microsoft.com/en-us/library/system.security.cryptography.sha1cng(v=vs.110).aspx

**Comment by KirillOsenkov** [comment]
You could create ILRepack.app.config with this switch:

```
    <AppContextSwitchOverrides value="Switch.System.Security.Cryptography.UseLegacyFipsThrow=false" />
```

See if this helps?

**Comment by KirillOsenkov** [comment]
Feel free to reopen if this is still an issue or if you need more info.
