### ISSUE TITLE
Rewrite generic parameter contraint on repack?

### ISSUE THREAD

**Issue by wmjordan** [gluck/il-repack#223]
As all of us know that it is impossible to use generic like this in C#:
````C#
class C<TEnum> where TEnum : Enum {
    public TNewEnum Convert<TNewEnum>(TEnum value)
              where TNewEnum : Enum {
         return (TNewEnum)value;
    }
}
````

Actually .NET CLR supports using `Enum` as a generic constraint, but C# compiler does not support that for some reason.
Is it possible to instruct ILRepack to rewrite the generic constraints replacing all `TEnum` and `TNewEnum` to `Enum` so we can get a result like the above?
````C#
class C<TEnum> where TEnum : IFormattable, IConvertible, IComparable {
    public TNewEnum Convert<TNewEnum>(TEnum value)
              where TNewEnum : IFormattable, IConvertible, IComparable {
         return (TNewEnum)Convert.ChangeType(Convert.ChangeType(value, typeof(TEnum).GetEnumUnderlyingType()), typeof(TNewEnum).GetEnumUnderlyingType());
    }
}

````

**Comment by gluck** [comment]
Hi,

If I understand what you want to achieve, then while it's surely possible for ILRepack to do it (as it rewrites IL), it's also well out of its scope/purpose, e.g. you'd want that for a single library, not only when merging assemblies together.
Consider looking towards [Fody](https://github.com/Fody/Fody) for that, quickly looking through its existing plugin list, it's even possible that [ExtraConstraints](https://github.com/Fody/ExtraConstraints) could achieve exactly what you want.

Cheers.

**Comment by wmjordan** [comment]
Thank you for mentioning _Fody_. I did read about it before.
I don't know whether it supports .NET versions before 4.5 well.
Do you think it worthwhile to build a similar plugin system to ILRepack, so people can do more with it?

**Comment by gluck** [comment]
Hi, I believe tools/libraries are better kept small & focused rather than multi-purpose.
In that respect, ILRepack should remain focused on merging libraries & dependencies (which already involves a lot of customization), and not venture in other IL manipulation areas.

A plugin system could make sense for all the merging-related features (WPF, Resources, Doc...), but not beyond that.
