### ISSUE TITLE
Merge assembly attributes conditionally

### ISSUE THREAD

**Issue by wmjordan** [gluck/il-repack#224]
We were merging several assemblies, one of which contained some `InternalsVisibleTo` attributes that were to be merged into the primary assembly. Currently ILRepack does not seem to be able to copy just those attributes from a specific assembly to the primary one. How to make it?

**Comment by gluck** [comment]
Today your options are:
- include these `InternalsVisibleTo` in the main assembly
- use 'copyAttr' option, but you'll get all assembly/module-level attributes from all merged assemblies
- use an `attributeFile` with all the attributes you want

Assuming none of these work for you and you want to cherry-pick only this specific attribute out of a merged assembly, there's no way to do just that.
I guess the use case is to merge some kind of reflexion/proxy library which needs internals access ?

**Comment by wmjordan** [comment]
The third option might be the way to go.
The problem came from this actually unresolved issue:
https://github.com/rpgmaker/NetJSON/issues/171

The serializer in the above case generates some dynamic types which access the internal methods in the library. The original library used `InternalsVisibleTo` to allow the access from those dynamic types.
After repacking, the library loses its identity and hence the trick fails.

**Comment by wmjordan** [comment]
If we were to support conditional merging attributes, what way do you think is the best to configure the repack engine?
1. Supply an external configuration file, formatted as XML or JSON, so it could be extended later with more functionalities
2. Add more parameters, for instance, `/copyAttr:ExternalA.dll#InternalsVisibleToAttribute /dropAttr:Primary.exe#InternalsVisibleToAttribute` to include the `InternalsVisibleTo` attribute from _External.dll_ and drop the ones in _Primary.exe_

**Comment by gluck** [comment]
sorry for the late reply, extending `copyAttr` sounds the best approach, something like aliasing current `/copyAttr` to `/copyAttr:*#*` and leveraging your syntax to reduce the scope of the attribute copying.

**Comment by wmjordan** [comment]
Alright.
Could you please tell me which code files shall I look into?

**Comment by gluck** [comment]
Sure:
[RepackOptions](https://github.com/gluck/il-repack/blob/master/ILRepack/RepackOptions.cs) is where you may modify the `CopyAttr` parameter (along with its [unit tests](https://github.com/gluck/il-repack/blob/master/ILRepack.Tests/RepackOptionsTests.cs))
[AttributesRepackStep](https://github.com/gluck/il-repack/blob/master/ILRepack/Steps/AttributesRepackStep.cs#L52) is where it is used and you need to implement the logic to pick the right attributes.

Cheers.

**Comment by wmjordan** [comment]
Well, I am now busy with my projects and companies too.
It seems that if this mechanism is implemented, you can also close PR #195.
I'll try to get some time for this project, if possible.
