### ISSUE TITLE
Failed to resolve System.Web.Http

### ISSUE THREAD

**Issue by kiranvolety** [gluck/il-repack#228]
When I'm trying to merge two dll's I'm getting the below exception

This is the command line I'm using:

```
C:\Users\XXX\Downloads\ilrepack.2.0.15\tools>ILRepack.exe /targetplatform:v4,
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319" /out:C:\Users\XXX\Desktop\output\client.dll C:\Users\XXX\Desktop\output\lib1.dll C:\Users\XXX\Desktop\output\lib2.dll
```

![2](https://user-images.githubusercontent.com/1023081/39080879-b3b76ff6-4554-11e8-8e37-181092b15d47.png)

**Comment by KirillOsenkov** [comment]
Try the latest version, also try the `/lib:<path>` option to specify the path to System.Web.Http.dll
