### ISSUE TITLE
merge dll  crash in unity

### ISSUE THREAD

**Issue by shwz** [gluck/il-repack#229]
two dll is ok，megered dll  is ok， can opened with ilspy or reflector，see is  normal， but when  use in  unity，direct crash，hope get some advice=。=

**Comment by deniszykov** [comment]
Can you provide crash information (log, dump)? And an example DLL would be nice too. Because without any details it is dead case.

**Comment by shwz** [comment]
[error.log](https://github.com/gluck/il-repack/files/2025287/error.log)

**Comment by shwz** [comment]
[Crash.zip](https://github.com/gluck/il-repack/files/2025352/Crash.zip)   mergedll  and dmp

**Comment by deniszykov** [comment]
Access violation in crash log and seems fine DLL. 

1) I saw 3 different version of Dotween in references, is it ok?
2) Do you have all referenced assemblies in you asset folder?
3) Try to add only this DLL without .pdb/.mdb files.

Unity version 2017.4.1 no crash on start-up. No error in logs either.

**Comment by shwz** [comment]
1, is  ok，all need
2，all referenced  assemblies in asset，if not，unity just error，not  crash
3，try and also crash

i am in company，so  must  use  the same unity version [version: Unity 5.6.3p3_88d4ddf6344a]

**Comment by shwz** [comment]
[Crash1.zip](https://github.com/gluck/il-repack/files/2025658/Crash1.zip)
can you try this

**Comment by deniszykov** [comment]
Still no crashes on Unity 2017.4.1

This is Unity-related problem, not ILRepack.
