### ISSUE TITLE
Merging identical types into one

### ISSUE THREAD

**Issue by deniszykov** [gluck/il-repack#231]
Currently when some dependency is merged twice ILRepack will duplicate and rename same types.
```
        A
      +   +
    B      C  <- cause duplication
   +
 C 
```

Ideally, I would like that one type would be discarded and the references to it would be replaced.
I understand that this is a big feature request so I offer my help and time:
1) I could write whole feature and PR it (cost me a some time to get into ILRepack pipelining code).
2) Write "comparison" code for TypeDefinitions and wait until you embed it.
3) Just wait :)

**Comment by gluck** [comment]
Can you clarify what you mean by same types ? Because if the letters in your drawing are assemblies, then merging `A+B+C` will rebind/internalize all `B` references to `C`.

Maybe you want to consider types with same name but different assembly to be re-mapped ?

**Comment by deniszykov** [comment]
I know that the same references are resolved and my example would merge fine if merged with one pass. But there 2 passes: 
1) B+C 
2) A + B 

I mean exactly same types. For example there is nice hash library "Hashy", every one is using "Hashy" and because it is really small it is embedded with ILRepack with /internalize flag. I develop my "BigApp" and choose 10 different libraries and each has embedded "Hashy" (because it is small and every one likes it). I merge all of them into my BigApp.dll and now has 10 copies of "Hashy" inside my merged assembly.

For real life example, SharpZipLib sometimes embedded.

**Comment by gluck** [comment]
Ok, assuming you're confident all the versions of C involved are identical, you may pass `/allowdup:Hashy.*` so that every type under that namespace will be 'merged into one' (which probably causes a mess if they are different, but should be a no-op if they are identical).

But maybe that doesn't work for you for some reason ?

**Comment by gluck** [comment]
All the magic ✨ happens in `RepackImporter.cs`, e.g. while [importing a type](https://github.com/gluck/il-repack/blob/a02073eecd111009597662c4f61840dc8c56fddc/ILRepack/RepackImporter.cs#L135) we check if it's already been imported (by name).
`DuplicateTypeAllowed` can be confusing and means "do we expect this type(s) to appear multiple times in the assemblies so we merge them together" (default behavior is to dedup/rename with unique names).

The existing risk with this approach is that the [comparison method](https://github.com/gluck/il-repack/blob/a02073eecd111009597662c4f61840dc8c56fddc/ILRepack/RepackImporter.cs#L348) used to check if a method already exists seems ... unreliable ...

But please have a look and enjoy 🎉

**Comment by deniszykov** [comment]
Thanks! 👍

**Comment by KirillOsenkov** [comment]
Does `/union` do what you want?

Doubt it does the deep diffing, it's not smart (I think?)

**Comment by deniszykov** [comment]
`/allowdup` helped me that time but I'm still thinking on implementing 
> Write "comparison" code for TypeDefinitions
and add `/allowdup=exactmatch` feature. 
I will close issue for now, and will try to allocate time for PR.
