### ISSUE TITLE
Type resolving problem after repack assembly with InternalsVisibleToAttribute

### ISSUE THREAD

**Issue by epeshk** [gluck/il-repack#233]
**Issue repro:** [https://github.com/epeshk/ilrepack-internalsvisibleto](https://github.com/epeshk/ilrepack-internalsvisibleto)

Suppose we have three assemblies: `A`, `B` and `C`. `B` references `C` and has `InternalsVisibleTo("A")` attribute. `A` references `B` and `C`.
Both `A` and `B` use type `Problem` from assembly `C`.

A.cs:
```csharp
internal static class A {
    public static void F() {
        B.F();
        Problem.MakeProblem();
    }
}
```

B.cs:
```csharp
using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo("A")]
internal static class B {
    public static void F() {
        Problem.MakeProblem();
    }
}
```

C.cs:
```csharp
public static class C {
    public static void MakeProblem(){ }
}
```

Then we pack `C` into `B`. `A` should continue use `C` as library.
We repack `B` in AfterBuild msbuild target with command: `ILRepack.exe /internalize /out:B.dll B.dll C.dll`

The build steps are executed in the following order: 

1. `C`
2. `B`
3. pack `C` into `B`
4. `A`

Now `A` references packed version of `B` which contains internal type `Problem`. Without `InternalsVisibleTo("A")` this type isn't visible from `A` and all things are going well. With attribute compiler can't decide between `Problem` from `B` and `Problem` from `C` so we got compilation error:
`error CS0433: The type 'Problem' exists in both 'B, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'C, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

To resolve this issue i propose adding ILRepack option `/renameInternalized` which force ILRepack to rename all types from other assemblies during repack, like duplicate types renaming:
`Problem` -> `<7fdc160b-0b9b-4c55-bc82-341aa12b7ab4>Problem`.

PR: https://github.com/gluck/il-repack/pull/232

**Comment by gluck** [comment]
Hi,

your PR looks good, but wouldn't it be a cleaner solution to strip the `IternalsVisibleTo` from `B(repacked)` ? It seems that's where your issue comes from, and even if the types are renamed, you don't really want them visible to `A` (e.g. it'll pollute intellisense).

Cheers.

**Comment by epeshk** [comment]
Hi, @gluck 

If we just strip `InternalsVisibleToAttribute` from `B(after repack)` we get runtime error in `A`:
`Unhandled Exception: System.MethodAccessException: Attempt by method 'LibA.F()' to access method 'LibB.F()' failed.`

So, if we decide to remove attribute, we must make type `B` in `B` public.
In case of this minimal repro it's simple. We just replace internal to public and everything works. But in real-world scenario it may be much more difficult. E.g. `B` can be inherited from other internal type `D` - then we will have to make `D` public too.  Or we just don't want the type `B` to be visible outside of projects in our solution. Or we will have to make public too many types. In other words, make some types public may be inacceptable, so we need InternalsVisibleTo attribute.

The primary purpose of this feature for me - repack assemblies without significant (internal -> public) changes in code.

About intellisense: ILRepack rename types to names which is invalid for C# (`<guid>typename` pattern) and IntelliSense don't show them (tested on VS 2017 with and without ReSharper and in Jetbrains Rider). So it feature is helpful to hide internals from intellisense in case with InternalsVisibleTo too.

Have a nice day!

**Comment by gluck** [comment]
Indeed, I missed the fact the attribute came from C (thought it came from C).

Thx !

**Comment by epeshk** [comment]
Cool! When new version appears in nuget?

**Comment by gluck** [comment]
No release planned (yet), though you can grab the CI build here: `https://ci.appveyor.com/api/projects/gluck/il-repack/artifacts/build/distributions/ILRepack.2.0.16.nupkg`

LMK if a nuget release is required for you.

**Comment by epeshk** [comment]
@gluck usage of ci build is not as convenient as usage tool from nuget package - requires more complicated CI (build configuration), not so easy to use for other developers (e.g. ILRepack used in [Vostok project](https://github.com/vostok/devtools/blob/master/library-dev-conventions/conventions.md), they want this feature too). It will be nice to see updated prerelease (beta) version in nuget.

**Comment by gluck** [comment]
Ok I'll plan a release for next week then.

Cheers.

**Comment by gluck** [comment]
... and released it is 🎉
