### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by iskiselev** [gluck/il-repack#238]
With CoreCLR 2.0 it is possible to run .NET Framework assemblies with CoreCLR, if they do not use anything not implemented in CoreCLR,
It means, that there is a chance that ILRepack will work on CoreCLR without recompilation, and I've tested it. For test, in ILRepack.exe folder I've created ILRepack.runtimeconfig.json with next content:
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0"
    }
  }
}
```

After it, I run it using `dotnet ILRepack.exe ...` command. And per my tests, it works! Unfortunately now it works on windows - as on unix environment it does Syscall.stat / Syscall.chmod, which are provided by mono and not exists in CoreCLR and crash after it.
To make it experimental runnable on Linux CoreCLR, we should call Mono API only when we are executed on mono.

**Comment by KirillOsenkov** [comment]
We have now released 2.0.22 which should support Unit and .NET 6/7/8:
https://github.com/gluck/il-repack/releases/tag/2.0.22

You can now run either `dotnet ILRepack.exe` or `mono ILRepack.exe` on Unix.

I have removed the dependency on Mono.Posix and shelling out to `stat` and `chmod` instead. Mono.Posix.Netstandard wouldn't have helped as it requires shipping a bunch of native platform binaries, and we are rewriting to ship a single standalone ILRepack.exe.

We are skipping source server info on non-Windows and emitting a warning.
