### ISSUE TITLE
Deterministic assembly creation

### ISSUE THREAD

**Issue by Thealexbarney** [gluck/il-repack#240]
With the recent changes done in Roslyn to allow reproducible builds, it would be useful in il-repack had that option as well.

As far as I can tell, there are at least 3 things preventing this, with 2 of them requiring changes to Cecil:
1. New names of renamed types
    This could be probably handled by producing a GUID from a hash of some of the type/assembly/etc. values.
2. The generated assembly's MVID
    Roslyn uses a hash of the assembly as a source for the MVID
3. The PE timestamp
    Roslyn also uses a hash for this field with the upper bit set dotnet/coreclr#1615

**Comment by KirillOsenkov** [comment]
The latest version should now produce deterministic assemblies.
