### ISSUE TITLE
Unable to merge .NET standard assemblies

### ISSUE THREAD

**Issue by praveenkrjha** [gluck/il-repack#243]
I followed the instructions in below post to merge .NET standard 2.0 assembly in Visual Studio 2017 for Mac:
https://www.meziantou.net/2018/08/28/merging-assemblies-using-ilrepack

It is a sample application with just nuget reference for Newtonsoft.Json and ILRepack.MSBuild.Task added (so that I can use the exact same csproj targets that was specified in above post).
However, I get below error:
`Error: Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' (ILRepackTemp)`

**Comment by vlindhol** [comment]
I have the same problem! Using ILRepack 2.0.18.

**Comment by bradwilson** [comment]
Bumping this issues because it's blocking me from moving from `ILRepack.MSBuild.Task` as well for https://github.com/xunit/xunit.

**Comment by KirillOsenkov** [comment]
I tried reproducing this using 2.0.18, 2.0.20 and the latest master, all seem to work fine for me on Windows. Unable to reproduce. Does anyone have more concrete repro steps? There must be a crucial detail about my environment that I'm missing.

**Comment by KirillOsenkov** [comment]
ah, OK, you're probably not passing the `-lib:` option:
`-lib:C:\xunit\src\xunit.v3.runner.tdnet\bin\Debug\netstandard2.0\ `

**Comment by KirillOsenkov** [comment]
try to ensure that both the working directory and the lib option are set to the directory containing the input .dlls.

I'll try to fix this so that specifying either one is sufficient.

**Comment by KirillOsenkov** [comment]
Cecil BaseAssemblyResolver resolves netstandard 2.0.0.0 from the GAC on Windows.

**Comment by bradwilson** [comment]
The failure is on non-Windows machines. The OP mentioned macOS, but it also fails for me on Linux.

**Comment by KirillOsenkov** [comment]
OK, I can repro this on Mac for both 2.0.18 and 2.0.20. 

@bradwilson I just published https://www.nuget.org/packages/ILRepack/2.0.21, it seems to be working, wanna try it out?

Just plop the ILRepack.exe on top of the one in your ILRepack.MSBuild.Task 2.0.13 NuGet.

**Comment by bradwilson** [comment]
@KirillOsenkov It is seemingly working, though with warnings:

![image](https://github.com/gluck/il-repack/assets/16944/2c777d5b-b5d9-4417-a83c-b771496b7f17)

**Comment by bradwilson** [comment]
I can ignore the warning output if they're benign. Here's the change set: https://github.com/xunit/xunit/commit/33898b4c8d828844a6befebed71b96193ae81889

**Comment by KirillOsenkov** [comment]
The warnings must have always been there, we now just print them better. You can ignore. Thanks for testing!
