### ISSUE TITLE
sqlite packing issue

### ISSUE THREAD

**Issue by j0shval3r0** [gluck/il-repack#245]
I am using Mono.Data.Sqlite (the NuGet package) for an application that I have.  Mono.Data.Sqlite requires the file sqlite3.dll (taken from the SQLite downloads page) to be in the same directory as it.  In order to be able to have people run my program without sqlite3.dll being in the same folder, I attempted to pack it (both into Mono.Data.Sqlite.dll and into my program) but it fails, giving me the following error:

Failed to load assembly \path\to\sqlite3.dll
System.InvalidOperationException: ILRepack does not support merging non-.NET libraries (e.g.: native libraries) ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.

Please tell me why this is happening, and what I can do to bundle sqlite3.dll
Thanks in advance!

**Comment by deniszykov** [comment]
Hi @j0shval3r0! You can't merge managed (.NET) and unmanaged (native) libraries. This is in theory possible, but not with ILrepack.

**Comment by j0shval3r0** [comment]
Thank you for clarifying!
Do you know of a tool that would allow me to merge unmanaged assemblies?  I tried Costura.Fody, but apperently that only works in Visual Studio and I'm working with Mono here.
Thanks again for your help with this

**Comment by KirillOsenkov** [comment]
The Costura.Fody approach is generally correct, but you can implement this yourself without using Costura.Fody. Just include sqlite3.dll as an embedded resource and at the beginning of your app write it to disk at the same directory as your app (if it's not there yet).

ILRepack can't help here.
