### ISSUE TITLE
Exception Throw by empty Win32Resource in CoreCLR

### ISSUE THREAD

**Issue by clamp03** [gluck/il-repack#252]
I am testing il-repack in CoreCLR. It improves memory usages and launching time in our environment. Thank you so much. :)
However, I found some issues and one of them is about empty Win32Resource.
When images don't have actual Win32Resource data, ILRepack generates an address (non-zero value) and a size (0 value) for Win32Resource  Then CoreCLR runtime checks whether the address is in a valid Win32Resource directory. The CoreCLR throws a BadImageFormat exception because there is no Win32Resource directory (its size is 0).

I can avoid this exception if I revert **Revert "Use Win32Resource directory only if there is actual data in it"**  in cecil. Could you let me know why the patch is reverted?
Thank you.

**Comment by timotei** [comment]
@clamp03 Can you please link the commit here? I can't find it

**Comment by clamp03** [comment]
Thank you for your reply.
It is in "gluck/cecil", not in "gluck/il-repack"
Link is https://github.com/gluck/cecil/commit/c854cad1a1da59ea94e5e87cbcc0b0a1416c9b62
