### ISSUE TITLE
How to merge only some assemblies?

### ISSUE THREAD

**Issue by rollsch** [gluck/il-repack#254]
I want to merge just 4 assemblies but not all the nuget package dlls as they are quite large and it increases load time if I do this.

How can I use ilrepack to just repack some DLLs but not all? If I try doing just some I get "failed to resolve assembly" errors.

**Comment by gluck** [comment]
Hi, yes you can, but you need to specify `/lib` argument(s) for ILRepack to find the referenced libraries (it won't merge them, but it still needs to load them), that's probably what you're missing.

Cheers.

**Comment by bastiflew** [comment]
I have a question tho: if I add some `other_assemblies` with the complete path, why in `Resolve()` method the full given path is not resolved first ?

**Comment by KirillOsenkov** [comment]
The resolver has improved significantly, please try the latest version.
