### ISSUE TITLE
ERROR: Failed to merge configuration files: System.ArgumentNullException: 'column' argument cannot be null.

### ISSUE THREAD

**Issue by rollsch** [gluck/il-repack#255]
I get the following error regarding "merge configuration files"

I'm assuming something is malformed within the config files themselves but I'm unsure what. How can I debug this?

> ERROR: Failed to merge configuration files: System.ArgumentNullException: 'column' argument cannot be null.
> Parameter name: column
>    at System.Data.DataKey..ctor(DataColumn[] columns, Boolean copyColumns)
>    at System.Data.Merger.GetSrcKey(DataTable src, DataTable dst)
>    at System.Data.Merger.MergeTable(DataTable src, DataTable dst)
>    at System.Data.Merger.MergeTableData(DataTable src)
>    at System.Data.Merger.MergeDataSet(DataSet source)
>    at System.Data.DataSet.Merge(DataSet dataSet, Boolean preserveChanges, MissingSchemaAction missingSchemaAction)
>    at System.Data.DataSet.Merge(DataSet dataSet)
>    at ILRepacking.ConfigMerger.Process(ILRepack repack) in C:\Temp\il-repack-2.0.17\ILRepack\ConfigMerger.cs:line 48
> INFO: Finished in 00:00:01.7749144

**Comment by rolandh** [comment]
I removed the following (redundant and I dont need it anymore) from one of my config files and it fixed the issue

>   <system.net>
>     <defaultProxy enabled="true" useDefaultCredentials="true">
>     </defaultProxy>
>   </system.net>
> 
>   
>   <compatibility xmlns="urn:schemas-microsoft.comn:compatibility.v1">
>     <application>   
>       <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
>     </application>
>   </compatibility>
>   <System.Windows.Forms.ApplicationConfigurationSection>
>     <add key="DpiAwareness" value="PerMonitorV2" />
>   </System.Windows.Forms.ApplicationConfigurationSection>
> 
>   <appSettings>
>     <add key="FileName" value=""/>
>     <add key="DeviceName" value=""/>
>     <add key="ClientSettingsProvider.ServiceUri" value=""/>
>   </appSettings>

**Comment by gluck** [comment]
Caused by the empty values at the bottom or something else from the file ?

**Comment by rolandh** [comment]
I believe so yes.

**Comment by KirillOsenkov** [comment]
We have rewritten the logic to merge config files, so this should no longer be an issue.
