### ISSUE TITLE
Failed to load assembly ;C:\Users\JanKostejn\.nuget\packages\ilrepack\2.0.17\tools\ILRepack.exe

### ISSUE THREAD

**Issue by honzakostejn** [gluck/il-repack#257]
Hi guys I ran to this issue and I know how to solve. I just want to make sure, that you guys can find the resolution and authors can look into it.

I did update from version 2.0.17 from 2.0.16 and it broke my build. I suppose it's something with the 'fullpath' variable in the Target triggered AfterTargets=Build:
![image](https://user-images.githubusercontent.com/32060653/60399182-16e8cf80-9b61-11e9-8a6d-62b78b069312.png)

The error I got after build is like this:
![image](https://user-images.githubusercontent.com/32060653/60399213-734bef00-9b61-11e9-945d-3f7904ae7b14.png)

So what I did? I just removed the nuget from my local machine:
![image](https://user-images.githubusercontent.com/32060653/60399221-ac845f00-9b61-11e9-97fe-2e26f81e2a0c.png)

And suddenly everything works:
![image](https://user-images.githubusercontent.com/32060653/60399237-e2c1de80-9b61-11e9-8066-5d9596f449c0.png)

From what I went through I'm not probably doing it by my custom Targets, it looks like the 'fullpath' variable cannot resolve multiple versions.

**Comment by honzakostejn** [comment]
Close it if you feel like this is not something that you should take care of. I just want to help other people that may end up in the same situation.
Thanks.

**Comment by Kirides** [comment]
This is what i use for ILRepack and it works for me.
It works because once you reference ILRepack in as `PackageReference` its `ILRepack.props` will be included, which automatically points to the currently installed version.

it would be even better, if it could automatically only include managed libraries, and not try to embed native libs

```xml
<Target Name="ILRepackWinExe"
        AfterTargets="Build"
        Condition=" '$(OutputType)|$(Configuration)' == 'WinExe|Release' ">
    <Error Condition="!Exists($(ILRepack))"
           Text="You are trying to use the ILRepack package, but it is not installed"/>
    <Exec Command="mkdir &quot;$(OutputPath)merged&quot; &amp; $(ILRepack) /out:&quot;$(OutputPath)merged\$(AssemblyName).exe&quot; /wildcards /internalize /target:winexe &quot;$(OutputPath)$(AssemblyName).exe&quot; &quot;$(OutputPath)*.dll&quot;"/>
</Target>
```
