### ISSUE TITLE
net 2.0 and net 4.0 merging

### ISSUE THREAD

**Issue by rollsch** [gluck/il-repack#258]
I have a .NET 2.0 assembly and a .NET 4.0 assembly. Is there any way to merge the 2.0 into a 4.0 assembly and tell it to use 2.0 still? I don't think this is possible but thought I would ask the question.

**Comment by timotei** [comment]
@rolandh There is a main assembly and the dependency assemblies. When you merge, the dependencies get merged into the main one. So if you merge it into the 4.0 then you will use 4.0, not 2.0.

What would be the usage example for this though? If you use .NET 4.0 APIs then for sure you can't run it on .NET 2.0 runtime

**Comment by rolandh** [comment]
Antinet only works as a 2.0 assembly (as it relies on specific implementations of the 2.0 runtime) so if you have a 4.0 assembly it means you cannot merge it. Not that big a deal and I assumed not possible but was worth asking the question.

**Comment by deniszykov** [comment]
@rolandh look like https://github.com/0xd4d/antinet has 4.0 version. Also just curious why some one need to prevent profiling debugging?

**Comment by rolandh** [comment]
The included main antinet project is 2.0 regardless of the 2.0 or 4.0 main project.

Google copy protection and you'll find millions of reasons to prevent debugging. Eg slowing the process of reverse engineering.
