### ISSUE TITLE
VS2019 WPF project fails to start (resource not found)

### ISSUE THREAD

**Issue by mr-const** [gluck/il-repack#266]
I created new WPF project in VS2019 with one form (MainWindow.xaml) and prism.dll, then tried to pack it into one executable, but it failed to start. However after I recreated (downgraded) project to default VS2017 WPF template (`<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
`), application started successfully.
Exception was:
```
System.Exception: The component 'MyApp.MainWindow' does not have a resource identified by the URI '/MyApp;component/mainwindow.xaml'.'
```

VS2019 csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <UseWPF>true</UseWPF>
    <StartupObject>MyApp.EntryPoint</StartupObject>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <_SettingsFiles Remove="Properties\Settings.settings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18" />
    <PackageReference Include="Prism.Core" Version="7.2.0.1422" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
```
I used MSBuild task for packing, don't think there will be difference, if I'll use tool version.

ILRepack.targets
```
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="ILRepacker" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">

    <ItemGroup>
      <InputAssemblies Include="$(TargetPath)" />
      <InputAssemblies Include="$(OutputPath)System.ValueTuple.dll" />
      <InputAssemblies Include="$(OutputPath)prism.dll" />
    </ItemGroup>
    <ILRepack
        Parallel="true"
        TargetKind="WinExe"
        Verbose="true"
        InputAssemblies="@(InputAssemblies)"
        OutputFile="$(OutputPath)MyApp.exe"
    />

  </Target>
</Project>
```

Entry point:
```
        [STAThread]
        public static int Main()
        {
            new Application().Run(new MainWindow());
            return 0;
        }
```

**Comment by mr-const** [comment]
I did some debugging and found out, that problem lies in OutputFile name. It must be equal to $(TargetFileName), otherwise resources won't load. Then it works with any project types, both old and 2019 style.
So are there any chances to change this behavior, or just state somewhere in the docs?

**Comment by timotei** [comment]
@mr-const The outputfile from il-repack (if that's the "OutputFile" you're talking about?), should have same name as input AFAIK, since, especially for Wpf we're having hardcoded references to the assembly name.

**Comment by mr-const** [comment]
Yes, about this option. I thought if I can rename output, why not to use it, but it turned out this option is more about output location, than about output file name in regard to WPF.
Anyway, WPF build is working now, so I think this issue can be closed.
