### ISSUE TITLE
Microsoft.CodeAnalysis Issue

### ISSUE THREAD

**Issue by VS-ux** [gluck/il-repack#272]
Hi all.
So recently I've been trying to change from [Costura.Fody](https://github.com/Fody/Costura) to something like `ILMerge`, due to a small startup cost from Fody. I have several dependencies, and ILRepack merges then great all except for [Roslyn](https://github.com/dotnet/roslyn) (Or more specifically `Microsoft.CodeAnalysis.Features` and a few other ones.) I would also like to point out that 5 assemblies (Microsoft.Build, and a few other ones) are intentionally not embedded because they require themselves to be in a real file, however, this is not related to Roslyn.
The first issue I ran into was duplicate types. I solved this with the internalize switch.
Then, I ran into the issue where those 5 assemblies were not present (I do not want to merge them). So I solved this by using the /lib switch. NOTE: I still got a lot of warnings saying: "WARN:  - Remove the assembly defining Microsoft.Build.Framework.IEventSource from the merge"

At this point, I got a merged binary. The binary booted, but as soon as I tried using features from `Microsoft.CodeAnalysis`, I got these weird `ArgumentOutOfRangeException` out of nowhere. I had hooked onto the `AssemblyResolve` event for those 5 binaries (NOT related to Microsoft.CodeAnalysis), but when I removed the EventHandler for that, I got a `FileNotFoundException` for Microsoft.CodeAnalysis.Features. Any idea why?
Thanks

EDIT:
So I just want to point out that before the merge, the 5 binaries were loaded correctly via `AssemblyResolve`. After the merge, those assemblies are not loaded properly.

EDIT 2:
Here is my full command:
`C:\users\myuser\path\to\ILRepack.exe /ndebug /parallel /wildcards /internalize /lib:"C:\Users\myuser\path\to\extra\binaries" /out:Merged\MyBinary.exe MyBinary.exe *.dll`

**Comment by KirillOsenkov** [comment]
Hi, it's hard to diagnose these issues without having access to the actual problem under debugger.
