### ISSUE TITLE
"Specified method is not supported" on net5.0

### ISSUE THREAD

**Issue by aalmada** [gluck/il-repack#273]
I'm using `ILRepack.MSBuild.Task 2.0.1` on `.NET 5.0.100-preview.7` with target framework `netstandard2.0`. 

I'm getting the following error when I run `dotnet build` on the command line:

```
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error : Specified method is not supported.
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at Mono.Cecil.ModuleParameters.GetCurrentRuntime()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at Mono.Cecil.ModuleParameters..ctor()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at ILRepacking.ILRepack.Repack()
C:\Projects\NetFabric.Hyperlinq\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj(31,5): error :    at ILRepack.MSBuild.Task.ILRepack.Execute()
```

I don't get the error when I build inside Visual Studio.

I reported the issue on Cecil (https://github.com/jbevain/cecil/issues/669) but it seems the issue is with ILRepack.

**Comment by sanikolov** [comment]
+1
agreed, getting the same on .net 5.0.

**Comment by lextm** [comment]
Related to https://github.com/gluck/il-repack/pull/236

**Comment by replaysMike** [comment]
bump, I believe this is fixed in Cecil now. Would be great to have an update for this as it's blocking .net 5 support for several of my packages.

**Comment by replaysMike** [comment]
actually, I rolled back my .Net 5 support and am still seeing the error in ILRepack 2.0.13.
`<TargetFrameworks>netstandard2.0;net48</TargetFrameworks>`

```
error : Specified method is not supported.
error :    at Mono.Cecil.ModuleParameters.GetCurrentRuntime()
error :    at Mono.Cecil.ModuleParameters..ctor()
error :    at ILRepacking.ILRepack.Repack()
error :    at ILRepack.MSBuild.Task.ILRepack.Execute()
```

**Comment by andrei-epure-sonarsource** [comment]
Is there any update?

**Comment by sanikolov** [comment]
I recommend the following alternative:

add this to your csproj
```
<PackageReference Include="ILMerge.Fody" Version="1.22.0" PrivateAssets="All" />
```
and then place lines like the following in the folder where the csproj lives (the filename must be `FodyWeavers.xml`)
```
﻿<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
      <ILMerge IncludeAssemblies='foo.bar.*|Newtonsoft.Json.*|etc' />
</Weavers>
```

This worked for me on .NET Core all the way to 6.0 and probably beyond.
I haven't tested it on any netfx version.

**Comment by chejunkie** [comment]
I have the exact same issue as @aalmada `ILRepack 2.0.18` in `.net6`. I tried @sanikolov solution but did not work for me.

**Comment by chejunkie** [comment]
I could not get ILRepack to work, but there was a more recent nuget that did the trick:

https://www.nuget.org/packages/ILRepack.Lib.MSBuild/2.1.18/

However, VS2022 still will not recognize the different DLL namespaces that were merged although dotPeek does not seem to have trouble reading them :/

**Comment by aalmada** [comment]
> Any chance this can work in .net 6.0? Works fine locally in VS 2022, but get this error in Azure Devops.
> 
> vmimage: windows-latest

I have the same issue with GitHub Actions. It works fine locally using [ILRepack.MSBuild.Task](https://github.com/peters/ILRepack.MSBuild.Task) on Visual Studio 2022.

Action report: https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer/actions/runs/5542153526/jobs/10116466992?pr=66

**Comment by aalmada** [comment]
Still having the issue when using GitHub actions. Here's today's action report: https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer/actions/runs/6498536288/job/17650070233?pr=78

**Comment by KirillOsenkov** [comment]
This should work fine with the latest ILRepack version: https://www.nuget.org/packages/ILRepack/2.0.23
