### ISSUE TITLE
Performance gain after using pdbstr when it is only needed

### ISSUE THREAD

**Issue by michalmalecki** [gluck/il-repack#274]
Below is to share my finding and check if it was considered before:
After profiling our build process (100 minutes on 20 cores, about 40 minutes spent in ilrepack) I saw in perfview that we spend a lot of time outside of ilrepack process, most likely in pdbstr. I realized that in our case we should actually not need pdbstr at all, as we don't embed source server information. After removing calls to pdbstr in private build of ilrepack, time spent for single project decreased from 23 to 11 seconds. Please note that this may be because of antivirus in big part, but is still very nice improvement. I'm proposing deferring extracting of pdbstr to time when it is needed, if it is needed.

**Comment by KirillOsenkov** [comment]
We have moved to a new version of Cecil that doesn't use pdbstr to work with pdbs, so this should hopefully no longer be an issue in the latest versions.
