### ISSUE TITLE
delaysign not working 

### ISSUE THREAD

**Issue by apoorv30gupta** [gluck/il-repack#276]
Hi,

I am trying to use ILrepack as an alternative to ILMerge to merge and delay sign the merged assembly. But it seems delay sign does not seem to work properly.
Sample command I use  : ILRepack.exe inputAssembly1.dll /keyfile:xyz.snk /delaysign /out:mergedAssembly.dll

using the command to check if the assembly is delay -signed : 
sn -vf mergedAssembly.dll
Output : Failed to verify assembly -- Strong Name Validation failed
![image](https://user-images.githubusercontent.com/16477015/93458985-af05dc80-f8fe-11ea-8b49-9ea233399a67.png)

Also checked the corflags of assembly manifest : 0x00000009
![image](https://user-images.githubusercontent.com/16477015/93459241-0e63ec80-f8ff-11ea-860a-509e6c6992ed.png)

Can anyone let me know what is the issue here ?

**Comment by KirillOsenkov** [comment]
This has just been fixed by https://github.com/gluck/il-repack/pull/330
