### ISSUE TITLE
ILRepack.sln fails to build with 499 errors in Visual Studio 2019 16.8.4

### ISSUE THREAD

**Issue by NeilJustice** [gluck/il-repack#280]
![image](https://user-images.githubusercontent.com/1912242/105568391-9f5c3180-5cfe-11eb-9ff0-3661116e1cbe.png)

![image](https://user-images.githubusercontent.com/1912242/105568396-a4b97c00-5cfe-11eb-8d3c-ff3021fb315a.png)

![image](https://user-images.githubusercontent.com/1912242/105568443-e3e7cd00-5cfe-11eb-8e36-0058fa944e58.png)

Thankfully I have a copy of ILRepack.exe version 2.0.16 which continues to work well. It would be nice to be able to upgrade to version 2.0.18 by building ILRepack.exe from source without experiencing build errors.

**Comment by ngyukman** [comment]
The project Mono.Ceil loading failed, I think it is because you didn't recursively clone the cecil?

**Comment by NeilJustice** [comment]
Thanks @ngyukman, `git clone --recursive https://github.com/gluck/il-repack` fixed the Mono-related build error messages.

Now a freshly-cloned ILRepack repository fails to build with VS 2019 due to this error message regarding ILRepack.Tests reference PresentationCore:

![image](https://user-images.githubusercontent.com/1912242/128612409-288cd2bf-5b88-4e6a-af3c-e77fee2312bf.png)

When ILRepack.Tests references PresentationCore and PresentationFramework are deleted and re-added, the PresentationCore-related error message is fixed, only to reveal these new build error messages in Start.xaml and End.xaml:

![image](https://user-images.githubusercontent.com/1912242/128612476-7b653069-7d19-4178-a7a2-f8246fd4764e.png)

**Comment by KirillOsenkov** [comment]
We have made significant changes so these errors are likely outdated. If you're still seeing problems with the latest version please file a new bug. Thanks!
