### ISSUE TITLE
Issue with Linux: "Failed to merge configuration files"

### ISSUE THREAD

**Issue by bradwilson** [gluck/il-repack#283]
When trying to run ILRepack against a .NET Framework application on Linux, I get an error which says that it failed to merge configuration files.

Repro:

1. Clone https://github.com/xunit/xunit
2. Run `git checkout 9195c0b` (this is on an in-progress branch, so I'm sending you to a moment in time)
3. Run `dotnet build src/xunit.v3.runner.console`

Working on Windows:

![image](https://user-images.githubusercontent.com/16944/109551416-6180c480-7a85-11eb-8140-f1a810c06b72.png)

Broken on Linux:

![image](https://user-images.githubusercontent.com/16944/109551695-bde3e400-7a85-11eb-8d4e-4543e6875e2d.png)

Our CI process uses the Linux build for making the official builds.

It does appear to be successfully running the repack, because it generates an executable which appears to run okay:

![image](https://user-images.githubusercontent.com/16944/109553382-d05f1d00-7a87-11eb-9026-51cb7824a04c.png)

I'm not sure what it's trying to do with the configuration file(s), but on the successful Windows side, the resulting "merged" `.exe.config` file is identical to original `.exe.config` file, except that the XML declaration has had `encoding="utf-8"` removed (why?) and `standalone="yes"` added (understandable). I would be happy to run ILRepack in such a way as to bypass .config file handling, since it would be just as easy for me to copy the original `.exe.config` file into the `merged` folder, but I didn't see any command line switch that would turn off config file processing.

I am invoking ILRepack via the executable:

![image](https://user-images.githubusercontent.com/16944/109552086-3e0a4980-7a86-11eb-8b62-d9e8af97ed83.png)

`dotnet --info` on Windows:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

`dotnet --info` on Linux:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  2.1.813 [/usr/share/dotnet/sdk]
  3.1.406 [/usr/share/dotnet/sdk]
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by bradwilson** [comment]
For the moment I've worked around the issue by copying all the to-be-merged files into a new `premerge` folder so that there's no `.config` files hanging around to trip the issue: https://github.com/xunit/xunit/blob/ea3007119bff2358873ac6fe0d922a60c5090f82/src/Directory.Build.targets#L11-L56

Will still appreciate a fix, though, so I can stop the unnecessary file copying.

**Comment by wmjordan** [comment]
This issue is really quite frustrating.
I encountered that before.

Maybe it is possible to add an option to merge the config file or not.
This is not so difficult to implement.

**Comment by KirillOsenkov** [comment]
Thanks @wmjordan for submitting the PR #291, the latest version has this option now: `/skipconfig`

Leaving the issue open to debug the underlying problem.

**Comment by KirillOsenkov** [comment]
Also the logic to merge config files was rewritten using XLinq, so it's likely it has been fixed accidentally, worth a check. Might not even need the /skipconfig now.

**Comment by KirillOsenkov** [comment]
Try https://www.nuget.org/packages/ILRepack/2.0.21, with and without `/skipconfig`

**Comment by wmjordan** [comment]
I just installed 2.0.21 and tried it on one of my production project, which was well merged by 2.0.15 before.
I got the following exception:
> System.Runtime.Serialization.SerializationException: Deserializing object failed. ---> System.Xml.XmlException: Invalid data on root element, line 1, position 1.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlUTF8TextReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at ILRepacking.Steps.ResourcesRepackStep.GetRepackListFromStream(Stream stream)
   at ILRepacking.Steps.ResourcesRepackStep.Perform()
   at ILRepacking.ILRepack.Repack()
   at ILRepacking.Application.Main(String[] args)

**Comment by bradwilson** [comment]
For my side, I can verify that the merge failure is gone now, using 2.0.21. I have been able to remove my premerge steps, and I verified that the only difference between the `.config` file in the unmerged folder and the `.config` file in the merged folder is that the merged version (benignly) added a UTF-8 BOM.

Change set (on top of the existing 2.0.21 upgrade in the commit prior): https://github.com/xunit/xunit/commit/920e3e521904741ffd2c1c100ef2073bbfa45cf5

**Comment by KirillOsenkov** [comment]
@wmjordan thanks for trying it out!

I found the regression and fixed in https://github.com/gluck/il-repack/commit/01b54ff113123da84d8283df0b70175549e926b0

Will publish a new release soon, need to do some testing and fix a couple unrelated bugs.

**Comment by KirillOsenkov** [comment]
I've now published https://www.nuget.org/packages/ILRepack/2.0.22

@wmjordan if you could try it out whenever you get a chance

@bradwilson you should now be able to call `dotnet ILRepack.exe` instead of `mono ILRepack.exe` on Unix, hopefully it'll work with both runtimes.

**Comment by KirillOsenkov** [comment]
I'll be closing this issue but please feel free to file new bugs if something else is wrong.

**Comment by wmjordan** [comment]
Hi, I downloaded the new version, used it on the previously reported project and it was working very well now.

**Comment by bradwilson** [comment]
Verified it works here as well. Thanks!
