### ISSUE TITLE
Use ILRepack as dotnet tool

### ISSUE THREAD

**Issue by bneumann** [gluck/il-repack#289]
Hi,

thanks for the awesome tool! I am about to migrate a cake script to use only dotnet cli. And I thought since cake already uses ILRepack as a standalone tool I could simply use dotnet tool as a replacement. 
But as I can see in the Nuget repo it is not recognized as a .NET tool.
It is a small change in the project file and most probably build and I also volunteer to do it if you guys want to have it also as dotnet tool.

Cheers

**Comment by KirillOsenkov** [comment]
Fixed by #364

**Comment by KirillOsenkov** [comment]
https://www.nuget.org/packages/dotnet-ilrepack
