### ISSUE TITLE
ILRepack fails to delay sign

### ISSUE THREAD

**Issue by slow-sun** [gluck/il-repack#290]
When trying to run ILRepack with delaySign, it seems that the output assembly cannot be delay-signed properly.

Parameters we set: `KeyFile="KeyFile" DelaySign=true TargetKind="Dll" OutputFile="OutputFile" InputAssemblies="InputAssemblies" CopyAttributes=true AllowMultiple=true Internalize="false" Verbose=true Parallel=true`
From the msbuild binlog, the parameters to ILRepack is set as expected.

Verify the assembly signing status with the sn tool:
`sn -vf assembly`
![image](https://user-images.githubusercontent.com/84044894/117883894-d5e39b00-b260-11eb-82f1-9811ceb42199.png)

And when we check the output assembly with ILSpy, it indicates that the merged assembly seems to be strong signed with the correct public key. This is weird.

Could anyone look into this please?

**Comment by arturfilar** [comment]
I've got same problem here :)

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/gluck/il-repack/pull/330
