### ISSUE TITLE
Can't specify multiple times /lib

### ISSUE THREAD

**Issue by sulan-blob** [gluck/il-repack#294]
Hey,

for some reason it doesn't work when I provide multiple /lib, here are the commands I use:

`./ILRepack.exe C:/Users/X/Desktop/A.exe /out:C:/Users/X/Desktop/SomeDir/A.exe /lib:C:/Users/X/Desktop/SomeDir /lib:C:/Users/X/Desktop/AnotherDir`

Only the first /lib is used, but not the second. Does anybody have a idea how the /lib is used multiple times?

Thanks for any help! :)

**Comment by KirillOsenkov** [comment]
Can you try the latest version? Seems to be working fine for me.
