### ISSUE TITLE
Does IL Repack remove unused members?

### ISSUE THREAD

**Issue by TonyValenti** [gluck/il-repack#295]
If I use IL Repack, is there an option to only include types that are used instead of the whole assembly?

**Comment by ngyukman** [comment]
iirc, I don't think there is such an option for that

**Comment by gluck** [comment]
IIRC if you internalize types, it'l only merged the types which as used:
e.g. `ILRepack A.dll B.dll /intern` will only expose A types and include B types used by A.

**Comment by KirillOsenkov** [comment]
Duplicate of #309
