### ISSUE TITLE
Include/Exclude Predicate for the "NuGet API"

### ISSUE THREAD

**Issue by MeFisto94** [gluck/il-repack#297]
Currently, IL Repack is coded with the feature parity towards ILMerge command line arguments in mind, but not using IL Repack as dependency.

As such, a good feature would be to be able to pass a predicate/`Func<Type, bool>`/delegate to the repacking process to determine which types should be included/merged in the process.

Currently, this can only be done with an attribute, which is why I need manual CECIL'ing to flag types that should be dropped in the process. It would be much better to allow the caller to just determine that via their criteria and only using predicates (i.e. NO RegEx or other solutions)

**Comment by KirillOsenkov** [comment]
We support the exclude file, read more at this issue:
https://github.com/gluck/il-repack/issues/323

`/internalize:"repackExclude.txt"`

**Comment by KirillOsenkov** [comment]
Keeping the issue open to document the exclude file in the command line help

**Comment by KirillOsenkov** [comment]
Can you try this:

```xml
  <ItemGroup>
    <InputAssemblies Include="$(OutputPath)*.dll" />
    <InputAssemblies Remove="$(OutputPath)grpc_csharp_ext.x86.dll" />
    <InputAssemblies Remove="$(OutputPath)grpc_csharp_ext.x64.dll" />
  </ItemGroup>
```

Then build your project from the command line using `msbuild /bl` and open the resulting msbuild.binlog using the viewer from https://msbuildlog.com.

In the viewer, verify that the two files you want excluded are actually excluded from the InputAssemblies item.
