### ISSUE TITLE
More granular Internalize excluding

### ISSUE THREAD

**Issue by i00** [gluck/il-repack#306]
Internalize has the ability to specify "excludefile"; however it would be good if you could also set exclusions given the full type name.

It would also be good to allow the user to setup their own attribute called something you specify e.g [RepackExcludeInternalize()] to prevent this from happening on the thing the attribute is on.

Thanks

**Comment by i00** [comment]
FYI The reason that created this was:
When a class within one of the secondary files and it requires XML de/serialization this fails as the class is not public if the internalized option was selected.

**Comment by KirillOsenkov** [comment]
Fixed in #307
