### ISSUE TITLE
Option to remove all non-referenced members from output assembly

### ISSUE THREAD

**Issue by i00** [gluck/il-repack#309]
It would be great to have an option to remove all items from an assembly that are non-referenced.
.. With an option to exclude specified attribute names (allow for multiple) - I guess the obfuscation one should be respected by default IF no command line switch is passed in
... and another option to remove private & friend only (to allow for public libs)

Thanks

**Comment by AlanHauge-Interacoustics** [comment]
I vote for this!

There should be a way to exclude specific classes / methods, also to ensure InternalVisibleTo does not break (for example for unit tests).
I'm not I'm a fan of attributing with ObfuscationAttribute, although it's a very simply solution (and I like those !).
An exclusion based on (part of) the full name in configuration would be better in my mind.

**Comment by lextm** [comment]
This is a reasonable but unrealistic feature request for a small open source project like this size.

Tree shaking algorithm isn't simple, and even Microsoft works on this for years and takes several .NET Core releases to improve it.

**Comment by deniszykov** [comment]
You can use [monolinker ](https://github.com/dotnet/runtime/tree/main/src/tools/illink)(which is used in Unity and Blazor) for it.

**Comment by KirillOsenkov** [comment]
Agreed, you can use ILLink on the merged assembly after the fact to tree-shake it. 

We do have a branch with a prototype of a linker here:
https://github.com/gluck/il-repack/tree/linker

However it's 8 years old, and stale and I don't know what the state of it was.

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/core/blob/main/samples/linker-instructions.md

**Comment by KirillOsenkov** [comment]
.NET now has an official tool that implements trimming (ILLink):
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0

I think we're unlikely to ever implement trimming ourselves in ILRepack. You can trim the output of ILRepack using ILLink in a separate step.
