### ISSUE TITLE
Specified method is not supported. #900

### ISSUE THREAD

**Issue by phani123hh** [gluck/il-repack#322]
I'm using ILRepack.MSBuild.Task 2.0.13 on .NET 7.0.202 with target netstandard2.0.
I don't get the error when I build inside Visual Studio.
I'm getting the following error when I run dotnet build on the command line:

![image](https://user-images.githubusercontent.com/80333615/227507666-ef21c602-0f06-4fab-b1b9-8073a71ba7c5.png)

Quick solution will be appreciated.

**Comment by phani123hh** [comment]
@hazzik @zippy1981 @vbfox @jonpryor 
Can anyone please help me on this

**Comment by chejunkie** [comment]
This is the same issue as [#273 ](url). See comments. You may have better luck with a different version, e.g.,
 https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task

**Comment by KirillOsenkov** [comment]
This should work fine with the latest ILRepack version: https://www.nuget.org/packages/ILRepack/2.0.23
