### ISSUE TITLE
Embedded PDB not handled properly

### ISSUE THREAD

**Issue by WenningQiu** [gluck/il-repack#325]
My application project and library projects uses "embedded" BuildType thus the PDB is embedded in the DLL and EXE files. When I try to debug il-repack'ed applications, the symbols cannot be loaded.

![image](https://github.com/gluck/il-repack/assets/4291622/1896d3a0-b776-44da-b6eb-57a0fb18c474)

However if I change DebugType to "full", the debugger would work fine.
 
That leads me to conclude that il-repack might not be handling embedded PDB properly.

**Comment by KirillOsenkov** [comment]
This should be fixed in the latest version (2.0.23 and newer: https://www.nuget.org/packages/ILRepack/2.0.23)
