### ISSUE TITLE
Proposal: Rename /ExcludeInternalizeSerializable to /InternalizeSerializable

### ISSUE THREAD

**Issue by mayermart** [gluck/il-repack#344]
`ExcludeInternalizeSerializable` is hard to read and understand.
Would it make sense to rename it to `InternalizeSerializable` or at least `InternalizeExcludeSerializable` ?

In my opinion it would better match the options `Internalize` and `InternalizeExclude`

**Comment by KirillOsenkov** [comment]
we want to internalize by default, so a flag needs to be the opposite of default. I know it does sound awkward, but it will be used very infrequently and users will figure it out. InternalizeExcludeSerializable is marginally better so not worth the churn, sorry.
