### ISSUE TITLE
Add developmentDependency to the nuspec

### ISSUE THREAD

**Issue by bradwilson** [gluck/il-repack#346]
The package right now does not specify `developmentDependency`, which means its gets added as a runtime dependency in generated packages.

Discovered while verifying the package result of adding an additional target framework.

![image](https://github.com/gluck/il-repack/assets/16944/0878505d-e909-4f3c-a19b-76fca92b6f2e)

**Comment by KirillOsenkov** [comment]
@bradwilson published https://www.nuget.org/packages/ILRepack/2.0.27, try it out

**Comment by bradwilson** [comment]
👍🏼 

![image](https://github.com/gluck/il-repack/assets/16944/a6498660-354e-4d71-b8ff-b0998652d9db)
