### ISSUE TITLE
Am I misunderstanding ILRepack / ILMerge

### ISSUE THREAD

**Issue by Aetherinox** [gluck/il-repack#349]
Does this application allow for merging DLL files only into one DLL, or does it also allow for DLL files to be merged into an EXE so that you only have to carry around a single exe.

Because I'm searching for the latter of the two, and after messing with it for a bit, it only seems to merge my DLLs, unless I'm missing some of the functionality of it.

**Comment by KirillOsenkov** [comment]
it’s both, you merge into a dll or an exe

**Comment by Aetherinox** [comment]
Thanks for the reply. Am I possibly doing something wrong then?

```
ILRepack.exe /out:"H:\Projects\demo\bin\Release\net481\publish\demoproject.exe" /lib:"H:\Projects\demo\bin\Release\net481\publish" /out:"H:\CSharpProjects\demo\bin\Release\net481\publish\demoproject.exe" "H:\Projects\demo\bin\Release\net481\publish\System.Management.Automation.dll"
```

Using absolute paths is what got me results, but all I was attempting to test was integrating the Powershell automation DLL into my exe. However, after the process completes, you can't launch the exe. It actually says that the program cannot be ran by windows, almost as if it's corrupted.

**Comment by KirillOsenkov** [comment]
your /out is specified twice

**Comment by Aetherinox** [comment]
Sorry, bad copy/paste from terminal. Yeah it only had one `/out`, just checked.

The size increases, but the file becomes corrupted.

**Comment by lextm** [comment]
The way you asked it shows much more red flags,

1. Whether assemblies (like `System.Management.Automation.dll`) can be merged and remain working the desired way varies. So, without knowing what are the exact assemblies you have at hand, this isn't a question others can answer.
2. A .exe file might or might not be a .NET assembly, and for .NET Framework projects and .NET (Core) ones the differences matter a lot. So, IL Repack might not be the right tool for you. For .NET (Core) projects, single file deployment is the right way to go.

I don't think you should attempt to use IL Repack or ILMerge for you .NET Framework executable. People have been used to that for more than two decades.

**Comment by KirillOsenkov** [comment]
oh, indeed, you can’t merge with a .NET apphost exe, it’s not a managed assembly. Merge with demoproject.dll, not demoproject.exe.

We should report an error when we detect this case.

**Comment by KirillOsenkov** [comment]
look into PublishSingleFile perhaps

**Comment by Aetherinox** [comment]
Thanks, I'll take a look.

I keep on .net 4.8.1 because most people have a lot of those libraries, including Powershell (the automation DLL), but I tried net8, and that powershell DLL is roughly 8MB. So I'd have to ship an 8MB file along with a 200kb exe, which just seems really odd.

I'll see what I can do with publish single file and try to play with this more.

**Comment by Aetherinox** [comment]
Just an update.

I spent 5 or so hours messing with all of this.

I was able to successfully do exactly what I wanted with the older ILMerge. The only thing of note was that the DLLs had to be merged in a certain order otherwise a series of random errors would occur, even stack exceptions.

But after running the exe on a brand new system, all the features work.

I now need to see if I can take that same process and try it with ILRepack. But I was able to do it with ILMerge just fine by building the exe and then utilizing the command-line.

**Comment by KirillOsenkov** [comment]
Keeping the issue open to issue an error when we attempt to merge a native exe/dll.

Would you mind pasting the exact command line you ended up using with ILMerge? I'm still curious if there's an actual bug in ILRepack here (other than you can't merge the apphost exe).

**Comment by Aetherinox** [comment]
Sure thing. To make it easier, I just created a batch file to run the build

```batch
SET PATH_ILMERGE=%USERPROFILE%\.nuget\packages\ilmerge\%ILMERGE_VERSION%\tools\net452

"%PATH_ILMERGE%"\ILMerge.exe bin\Publish\demoapp.exe  ^
    /lib:bin\Publish ^
    /out:bin\Publish\demoapp.exe ^
    System.Buffers.dll ^
    System.Numerics.Vectors.dll ^
    System.Memory.dll
```

Was relatively straight forward with ILMerge. I haven't had a lot of time lately, but I do want to go back and try again with li repack. I'd rather use the updated program and not rely on the old version.

But as soon as I combine the DLLs in this order, everything works perfect.

**Comment by KirillOsenkov** [comment]
Let me know if you still see issues. If there are still problems I'll need a detailed repro and the logs (`/verbose /log:log.txt`)
