### ISSUE TITLE
Feature suggestion: Provide a comma-separated list of assemblies to be internalized

### ISSUE THREAD

**Issue by peters** [gluck/il-repack#35]
See https://github.com/peters/ILRepack.MSBuild.Task/issues/2

**Comment by cwellsx** [comment]
I think you implemented this by letting the user specify a filename after the /internalise command-line parameter, of a file which contains lines of text, which are regexps which specify the names of types which shouldn't be internalised.

BUT I think you didn't update the README.md which documents the command-line parameters ... the README currently only says,

    - /internalize         sets all types but the ones from the first assembly 'internal'
