### ISSUE TITLE
Exceptions aren't renamed?

### ISSUE THREAD

**Issue by johnterickson** [gluck/il-repack#350]
It looks like exceptions aren't renamed.  Is this expected or should I fork and PR?

repro: 
git clone https://github.com/microsoft/MSBuildCache.git
git checkout 8bc8b88c216f3854c5c256c794e5fe912717f6e0
dotnet build MSBuildCache.sln --configuration Release /bl

![Image](https://github.com/gluck/il-repack/assets/10488772/b70a8e52-0f33-4b72-a79e-a75f74fac8e3)

**Comment by KirillOsenkov** [comment]
We don't rename types marked as serializable but there's a command line option to override that

**Comment by johnterickson** [comment]
It's @KirillOsenkov! Thank you, sir :)

**Comment by johnterickson** [comment]
Ah looks like this was fixed in 2.026.  I was on 2.025.  Keep up the great work!
