### ISSUE TITLE
Add an Icon to the nuget package

### ISSUE THREAD

**Issue by TraGicCode** [gluck/il-repack#354]
Is it possible to have an icon added to the il-repack NuGet package? Currently, I am the maintainer of the Chocolatey package for il-repack, and one of the requirements for Chocolatey is that I provide a valid icon. While I can simply 'make something up,' it would be beneficial if there was an official icon associated with the NuGet package that I could also use as part of the Chocolatey package.

il-repack on chocolatey.org ( https://community.chocolatey.org/packages/il-repack )

**Comment by KirillOsenkov** [comment]
I'm not great with icons, but don't think we care too much.

Here's something:
https://github.com/gluck/il-repack/commit/3b5334fdf8e298957b0a6e27a8472708316d29a3
