### ISSUE TITLE
Disable source server warning on unix

### ISSUE THREAD

**Issue by Tejes** [gluck/il-repack#356]
Is there a way to disable the warning message introduced in #176? I use kekyo/ILRepack.FullAuto and this message is included in my build output as a warning, which is undesirable to say the least.

A new switch to disable source server data processing completely would be a good solution in my opinion.

**Comment by KirillOsenkov** [comment]
Agreed, the warning is just not useful. I deleted it.

**Comment by KirillOsenkov** [comment]
published in 2.0.29
