### ISSUE TITLE
Possible Internalize regression

### ISSUE THREAD

**Issue by Aragas** [gluck/il-repack#357]
Good day!
It seems that there's a regression in v2.0.29 with internalize. Simply setting the `--internalize` flag triggers an error "Input file not found: --internalize"
Based on the recent commits, I believe the idea was to add an optional list of files with the flags, but it might not work now when no files are provided at all

**Comment by mattleibow** [comment]
Seems they are public from 2.0.24. At least that is the version I tested. 2.0.18 was still internal.

**Comment by KirillOsenkov** [comment]
OK will look into internalizing Cecil, sorry about all the regressions

**Comment by KirillOsenkov** [comment]
Filed #358 to track it separately

**Comment by KirillOsenkov** [comment]
Published 2.0.30, please try it out:
https://www.nuget.org/packages/ILRepack/2.0.30
https://www.nuget.org/packages/ILRepack.Lib/2.0.30
