### ISSUE TITLE
Getting "Method reference is used with definition return type / parameter." / Due to TypeForwardedTo type

### ISSUE THREAD

**Issue by deniszykov** [gluck/il-repack#359]
Issue:
====

I'm getting following warning message:
```
WARNING: Method reference is used with definition return type / parameter. Indicates a likely invalid set of assemblies, consider one of the following
WARNING:  - Remove the assembly defining Microsoft.Extensions.DependencyInjection.IServiceCollection from the merge
WARNING:  - Add assembly defining Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.Logging.ILoggingBuilder::get_Services() to the merge
```
Because `ReferenceFixator` is failing to map declaring type of `ILoggingBuilder::get_Services()` method in ReferenceFixator.cs: 436
```cs
TypeReference declaringType = Fix(method.DeclaringType);
```
and it is failing because `TypeReference.Scope` for `method.DeclaringType`  is **Microsoft.Extensions.Logging** while type is declared in **Microsoft.Extensions.Logging.Abstractions** and being forwarded:

```cs 
// Microsoft.Extensions.Logging, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
[assembly: TypeForwardedTo(typeof(ILoggingBuilder))]
```

Steps to reproduce:
============

1) Take these assemblies
2) Merge them 

```sh
/target:exe  "/lib:%UserProfile%\.nuget\packages\microsoft.netcore.app.ref\6.0.0\ref\net6.0" "/out:Test.dll" "Microsoft.Extensions.Logging.Configuration.dll" "Microsoft.Extensions.DependencyInjection.Abstractions.dll" "Microsoft.Extensions.DependencyInjection.dll"  "Microsoft.Extensions.Logging.Abstractions.dll"
```
[libs.zip](https://github.com/gluck/il-repack/files/14887802/libs.zip)

Expected:
======

Type forwarding is respected. Probably type is registered twice in `MappingHandler` with both scopes when it is forwarded.

**Comment by deniszykov** [comment]
I tried to investigate further and trail gone cold in RepackImporter.cs:50 at `Import(ExportedType type, Collection<ExportedType> col, ModuleDefinition module)`. 
Type forwards are processed there, but not I think incorrectly.

**Comment by KirillOsenkov** [comment]
The exported type ILoggingBuilder is being skipped here:

![image](https://github.com/gluck/il-repack/assets/679326/92fbcef7-e0d0-49d0-86f2-e757b698bf88)

I'm guessing we erase all memory of it being a forwarded type, we still need to remember that it was a forwarded type even though it's being rewritten

**Comment by KirillOsenkov** [comment]
Assembly reference graph for reference:
![image](https://github.com/gluck/il-repack/assets/679326/954e6b4a-02cf-4d5b-a9ec-a5ac8885587a)

**Comment by KirillOsenkov** [comment]
we can remove Microsoft.Extensions.Logging.Configuration from tests to minimize the repro

**Comment by KirillOsenkov** [comment]
if I remove that continue statement, I no longer get the warning about ILoggingBuilder

**Comment by KirillOsenkov** [comment]
Actually I think this may not be a bug at all. I have enhanced to warning to specify more details:

![image](https://github.com/gluck/il-repack/assets/679326/f8db6048-3ccb-4f6e-a85a-edd4b4f629ed)

When rewriting the body of this method we encounter the AddOptions() extension method call:
![image](https://github.com/gluck/il-repack/assets/679326/650af6d3-0e39-42f6-8121-ff106a9e564c)

and that method is defined in Microsoft.Extensions.Options:
![image](https://github.com/gluck/il-repack/assets/679326/847c6631-04cf-43b5-a478-0b299f7d8139)

So the warning is technically correct, we should either Remove the assembly defining Microsoft.Extensions.DependencyInjection.IServiceCollection from the merge (Microsoft.Extensions.DependencyInjection.Abstractions.dll) 

or 

add Microsoft.Extensions.Options.

When I add Microsoft.Extensions.Options.dll, the warnings go away.

**Comment by deniszykov** [comment]
With better diagnostic message I have found and fixed most on these warning, but not all. One is left:
```
Add assembly defining <>f__AnonymousType4`2<System.String,System.Collections.Generic.Dictionary`2<System.String,Serilog.Settings.Configuration.IConfigurationArgumentValue>> Serilog.Settings.Configuration.ConfigurationReader/<>c::<GetMethodCalls>b__20_1
(Microsoft.Extensions.Configuration.IConfigurationSection) to the merge: <MY_PROJECT_ASSEMBLY_NAME>
```
of course ` <MY_PROJECT_ASSEMBLY_NAME>` is included in merge. I will report back later.

**Comment by deniszykov** [comment]
Unfortunately I can't just isolate this case as a small set of assemblies. But I found that if I move this code a little lower, the problem disappears:

![image](https://github.com/gluck/il-repack/assets/10157332/5e0b250f-8fe4-4934-a725-3c632954686a)

Because `method.ReturnType` is not matching 

![image](https://github.com/gluck/il-repack/assets/10157332/778aaa03-4f74-4cd9-afa1-d340c03ac1e3)

Due to rename of anonymous type `<>f__AnonymousType4`2` to `<18c72155-01ef-4bc4-9d93-2a702bceba97><>f__AnonymousType4`2` 

![image](https://github.com/gluck/il-repack/assets/10157332/935ea133-5d74-4a7d-9ec7-bf5baf09d347)

**Comment by KirillOsenkov** [comment]
can you send me your full list of assemblies so I can debug too?

**Comment by deniszykov** [comment]
I can't send you all my libraries because it is private project. But I'm trying to create minimal repro:
And I'm stuck with strange merge behavior:

![image](https://github.com/gluck/il-repack/assets/10157332/9d9dbac1-1a3d-4e41-8d4a-3b294b531ab8)

I have 2 types: 
ClassLibrary1 -> <root namespace>.MyGenericType<T1, T2>
ClassLibrary2 -> <root namespace>.MyGenericType<T1, T2>

both have default `.ctr` and different fields.

After merge I get one merged type with only ONE constructor. My thoughts it is breaking behavior.

[merge_on_type.zip](https://github.com/gluck/il-repack/files/14921655/merge_on_type.zip)

I'm still working on minimal repro.

**Comment by deniszykov** [comment]
Also I found that `/internalize` rename/mangle public class and keep name of internalized.

`/target:exe /internalize /lib:<user>\.nuget\packages\microsoft.netcore.app.ref\6.0.0\ref\net6.0 /out:Test.dll ClassLibrary1.dll ClassLibrary2.dll`

![image](https://github.com/gluck/il-repack/assets/10157332/d9191b42-ebea-492c-9e45-c8bd6302b1ae)
[libs_internalize.zip](https://github.com/gluck/il-repack/files/14921778/libs_internalize.zip)

**Comment by deniszykov** [comment]
It's taking too much time to reproduce these circumstances. 
I'm gladly present debugging session for you @KirillOsenkov in skype(deniszykov87)/discord (490096546608578560)/telegram(deniszykov) during evenings or mornings in CET.

**Comment by AlexeyZarubin** [comment]
I met the same issue with TypeForwardingTo and Microsoft.Extensions.Logging library. 
Are there any plans to fix this bug or maybe there is a workaround?

**Comment by KirillOsenkov** [comment]
A small self-contained repro would help here

**Comment by AlexeyZarubin** [comment]
> A small self-contained repro would help here

Ok, let me work on it.

**Comment by AlexeyZarubin** [comment]
> A small self-contained repro would help here

Here it is, please follow readme:
https://github.com/AlexeyZarubin/IL-repack-issue-demo/tree/main

Thanks for a help!

**Comment by AlexeyZarubin** [comment]
@KirillOsenkov Did you have a chance to test the issue?

**Comment by KirillOsenkov** [comment]
I hope I'll have time this weekend

**Comment by AlexeyZarubin** [comment]
Hi @KirillOsenkov. Any updates?

**Comment by KirillOsenkov** [comment]
Please give the latest commit a try (I haven't published a new version of the NuGet package yet)

**Comment by KirillOsenkov** [comment]
Published 
https://www.nuget.org/packages/ILRepack/2.0.34
https://www.nuget.org/packages/ILRepack.Lib/2.0.34

**Comment by AlexeyZarubin** [comment]
This is a great fix, thank you for your help!
