### ISSUE TITLE
Replacement for AllowDuplicateType Method of ILMerge

### ISSUE THREAD

**Issue by sk185828** [gluck/il-repack#360]
There was a method with ILMerge which used to take typeName in string format as a input to allow those type of assemblies to be duplicated .    The syntax is given below

public void AllowDuplicateType(string typeName);

**Comment by KirillOsenkov** [comment]
do you have a small example perhaps or a unit-test?

**Comment by sk185828** [comment]
This is the code snippet which was written with ILMerge now I am trying to do the same with ILRepack . Here you will be able to see the method ILMerge.AllowDuplicateType
            var mainAssemblyName = args[0].ToLower();
            var assemblyBinFolder = args[1];
            var finalBinFolder = args[2];
            var specifiedVersion = "/v40";
            var allowDup = false;
            List<string> duplicateTypeList = null;

            if (args.Length > 3)
            {
                if (args[3].ToLower().StartsWith("/v4"))
                {
                    specifiedVersion = args[3];
                }

                var arg = args.Skip(3).FirstOrDefault(s => s.ToLower().StartsWith("/allowdup"));
                if (arg != null)
                {
                    allowDup = true;
                    var s = arg.Split(':');
                    if (s.Length > 1)
                    {
                        duplicateTypeList = s[1].Split(',').ToList();
                    }
                }
            }

           ilmerge.FileAlignment = 512;
            ilmerge.OutputFile = Path.Combine(finalBinFolder, mainAssemblyName);
            ilmerge.SetInputAssemblies(properInputAssemblies);

 if (allowDup)
            {
                if (duplicateTypeList == null)
                {
                    ilmerge.AllowDuplicateType(null);
                }
                else
                {
                    duplicateTypeList.ForEach(ilmerge.AllowDuplicateType);
                }
            }

            ilmerge.Log = true;
            ilmerge.Merge();

**Comment by KirillOsenkov** [comment]
ILRepack already supports both the `/allowdup` command-line arguments:
![image](https://github.com/gluck/il-repack/assets/679326/6a246183-5d2a-433f-bd6c-3519a753803e)

I just made AllowDuplicateType public:
https://github.com/gluck/il-repack/commit/bc568451f0ca360ab7cea57caca4877db77e305f

I also made AllowAllDuplicateTypes settable:
https://github.com/gluck/il-repack/commit/79d83e6a3ed3551f466aff69153061c0246afb75

But even today you can do this:

![image](https://github.com/gluck/il-repack/assets/679326/c773d982-bc0d-404c-a763-d664d54b3667)

**Comment by nickpreston24** [comment]
Great, good stuff.  But how do we configure it in the .props file or the .targets file?

I see documentation for the CLI commands, but that's not what I'm after.  I keep getting a type conflict between a 3rd party library and MSFT's Dependency Injection library, even though I'm not using the Attribute specified in the error below:

![Image](https://github.com/user-attachments/assets/ba27e2c7-c404-41a5-9b24-91cfe424f4ce)

Here are my attempts in the .props:

![Image](https://github.com/user-attachments/assets/02f1adf0-4fde-435f-9adf-dc72f133fada)

And here's my .target:

![Image](https://github.com/user-attachments/assets/7a3a746e-a2af-4687-aa30-c82ca14994ae)
