### ISSUE TITLE
Possible bug with internalizing assemblies?

### ISSUE THREAD

**Issue by peters** [gluck/il-repack#37]
Say you have 4 assemblies, where 3 are internalized and the last one is not. You reference the resulting dll in a new project. Say the main assembly is A, and the namespace of the assembly merged that was not interalized is B. Trying to reference namespace B in this project will not work, because it is not recognized in visual studio.

Interesting enough, if you view the object browser (or in ilspy for that matter) namespace B is clearly available in the merged assembly. 

Also if you try to add assembly B as a solution project reference, visual studio complains that assembly B is available in both the merged assembly and the solution project reference.

Any ideas of what could be wrong?

**Comment by KirillOsenkov** [comment]
It's hard to say now.
