### ISSUE TITLE
Feature request: Changing anycpu <-> anycpu32bitpreferred

### ISSUE THREAD

**Issue by leppie** [gluck/il-repack#373]
I know it is a bit pedantic, but corflags allows one to change the Cor20 flags. 

I am not aware of a non-NET Framework replacement. Might be a nice addition. 

(not sure if this has any relevance to .NET Core, also just applies to exes)

Corflags uses the following syntax (inplace modification):

```
corflags file.exe /32bit+
```

I suggest that and `/32bit-` for removal. Instead of inplace, use out arg.

![image](https://github.com/user-attachments/assets/3057ae35-d169-4cec-8686-d26f85368ca5)

Note: Adding suggestion as I think it is easy to do and fits in with an assembly modifier.

**Comment by leppie** [comment]
I will give this a go if approved.

**Comment by KirillOsenkov** [comment]
this should be a separate tool, see for example 
https://github.com/KirillOsenkov/MetadataTools/tree/main/src

**Comment by leppie** [comment]
Oh, thats cool. I knew some of my tools arent useful here, but they might be there.
