### ISSUE TITLE
Feature request: AL 'embed' replacement

### ISSUE THREAD

**Issue by leppie** [gluck/il-repack#374]
Add support for `/embed` flags as used by AL.

This basically just adds manifest resources.

Flag syntax:

```
file[,name]
```

Example:

```
/embed:"..\netcoreapp2.1\IronScheme.FrameworkPAL.dll",core-IronScheme.FrameworkPAL.dll
```

Realworld example:

I use this to just combine a bunch of files as resources into an assembly (which is later merged).

```
al /out:IronScheme.PALResources.dll /embed:IronScheme.FrameworkPAL.dll /embed:"..\netcoreapp2.1\IronScheme.FrameworkPAL.dll",core-IronScheme.FrameworkPAL.dll /embed:"..\net9.0\net9-IronScheme.FrameworkPAL.dll"
ilrepack /out:merged\IronScheme.dll IronScheme.dll ... IronScheme.PALResources.dll
```
Single or double step would be nice.

Note: Adding suggestion as I think it is easy to do and fits in with an assembly modifier.

**Comment by KirillOsenkov** [comment]
I think this should be a separate tool. ILRepack is not a swiss army knife for metadata, it should do one thing and do it well: merge assemblies.

There are multiple workarounds: as you mention, al exists and does the job. 

Additionally, embedding a resource into a .dll is as easy as adding an EmbeddedResource item to the .csproj:
https://github.com/KirillOsenkov/MSBuildTools/blob/77d80a2d6d28439666f4620f12d80ddfa5217fe0/src/SimpleResource/SimpleResource.csproj#L9
