### ISSUE TITLE
Dotnet tool version of ILRepack is out of date

### ISSUE THREAD

**Issue by fourpastmidnight** [gluck/il-repack#379]
The `dotnet tool` version of ILRepack is still only v1.0.1 even though the release notes for v2.0.35 state that it's possible to install ILRepack as a `dotnet tool` and one would expect that the version installed would be the latest version, 2.0.35.

**Comment by fourpastmidnight** [comment]
OK, thankfully, when issuing `ilrepack /help`, the version string of the tool includes the git SHA of the commit that produced the tool. And, even though the version says 1.0.1, the git SHA is from a commit only back in this past September just a few weeks ago. So, it's not _that_ old. BUT, looking through all the releases, there is not a single "official" release which corresponds to the git SHA of the dotnet tool version of ILRepack.

It would be nice if, when a release is created, that the dotnet tool version of the release would also be created at the same time, and that the executable version for that release would match the GitHub release version of the release. (Package versions _can_ be different, as the version of a package does not necessarily need to be tied to the version of the executable inside&mdash;though it is helpful if it is; but sometimes it's not possible, e.g., a packaging error that requires a new package to be released even if the contents inside have not changed, is a perfectly good reason for a package version to differ from the package contents version.)

**Comment by KirillOsenkov** [comment]
yes they are not synced and this is by design, such that the library and the tool can evolve independently if needed.

**Comment by KirillOsenkov** [comment]
I'll try to publish the tool and the library in the same release next time.
