### ISSUE TITLE
Wrong PE timestamp

### ISSUE THREAD

**Issue by myhomeiot** [gluck/il-repack#380]
Last version which put correct PE timestamp it's 2.0.22 all newer put some garbage on this field (each time different).
Its may be cecil issue or ILRepack should do some extra things for this.

Thanks for great project!

**Comment by KirillOsenkov** [comment]
The timestamp is now a deterministic hash of the contents. Now when you repack the same inputs you'll get the same bytes out every time. This is how the Roslyn C# compiler works too in deterministic mode.

Curious how did you find it? Why is the timestamp important for your case?

**Comment by myhomeiot** [comment]
Ah, somehow I missed it when look into sources.

I find it because use it as compilation timestamp and it's shows in the log ;-)

I use .NET Framework 4 which doesn't have deterministic compilation option, so for me it's pointless.

Maybe it's will be good idea to make the option to preserve timestamp or change it to the hash only if original timestamp from Roslyn C# compiler. As I check it always has zero in 2 lower bytes:
.NET 6: 670D0000 time date stamp Mon Oct 14 14:26:56 2024
.NET 7: 66470000 time date stamp Fri May 17 09:58:08 2024
.NET 8: 67110000 time date stamp Thu Oct 17 15:16:00 2024
.NET 9: 67200000 time date stamp Mon Oct 28 23:20:00 2024

**Comment by KirillOsenkov** [comment]
would you consider something like AssemblyInformationalVersion to bake the timestamp into your assembly and then use Reflection to read it? 

How are you reading the PE timestamp right now?

You could also write a simple tool that will replace the timestamp in the PE file with whatever you want, it's relatively easy to do.

This is where the timestamp is being computed:
https://github.com/gluck/il-repack/blob/0856f03c43998dd5cb4fed83983bbe2b21b2db0e/ILRepack/ILRepack.cs#L450

**Comment by KirillOsenkov** [comment]
or perhaps something like https://www.nuget.org/packages/ThisAssembly.Git

**Comment by myhomeiot** [comment]
> How are you reading the PE timestamp right now?

The project very old, so it's use something like [this](https://gist.github.com/b0urb4k1/ef386f9075d1f74fdff607f306743954)
I need to also to read Machine and ImageFileLargeAddressAware flag. I just move from ilmerge 3.0.29 to ILRepack because add ARM64 support and ilmerge doesn't work correctly with ARM64 assembly's.

I'm happy with ILRepack 2.0.22 ;-)

**Comment by KirillOsenkov** [comment]
You could write the timestamp exactly the same way after you repack

**Comment by KirillOsenkov** [comment]
We could also make an option to use a real timestamp instead of the deterministic one, it's just I'm afraid your use case is very limited and it's not worth it.

**Comment by myhomeiot** [comment]
> We could also make an option to use a real timestamp instead of the deterministic one, it's just I'm afraid your use case is very limited and it's not worth it.

Agreed the use case is very limited.
I will use modified version, the changes I put into PR which you can reject/merge.
Thanks for your help.

**Comment by KirillOsenkov** [comment]
I'll take it since you've done the work and it looks reasonable! Thanks!

**Comment by KirillOsenkov** [comment]
Published https://github.com/gluck/il-repack/releases/tag/2.0.36

**Comment by myhomeiot** [comment]
Thanks!
