### ISSUE TITLE
unable to fix reference already merged into reference assembly

### ISSUE THREAD

**Issue by thejuan** [gluck/il-repack#43]
I am attempting to merge MassTransit 2.8 and Magnum into my own assembly.
Magnum has Newtown.Json merged already into itself, MassTransit references a different version.

Using the latest IL-Repack from Nuget
I get this error

WARN: Method reference is used with definition return type / parameter. Indicates a likely invalid set of assemblies, consider one of the following
WARN:  - Remove the assembly defining Newtonsoft.Json.Utilities.<22393bc1-1b24-4381-8b42-1e880f8e1d97>IWrappedDictionary from the merge
WARN:  - Add assembly defining Newtonsoft.Json.Utilities.<22393bc1-1b24-4381-8b42-1e880f8e1d97>IWrappedDictionary Newtonsoft.Json.Serialization.JsonDictionaryContract::CreateWra
pper(System.Object) to the merge

A type load expection if i try and use the DLL (enumerate the types in it)

**Comment by dennisdoomen** [comment]
I'm observing the exact same problem with this public repository: https://github.com/dennisdoomen/piercer/tree/AttemptToUseILRepack

**Comment by emysa341** [comment]
Same warnings on my side, any fix ?
