### ISSUE TITLE
Feature request: namespace mapping when merging assemblies

### ISSUE THREAD

**Issue by nikhilk** [gluck/il-repack#6]
I have a scenario where it would be interesting to collapse/remap the namespace of types from assemblies being referenced and internalized when merging assemblies. For example:
- Assembly A references assembly B (which contains namespaces such as B.X, B.Y, etc.)
- Assembly B references assembly C (which contains namespaces such as C.Foo, C.Bar, etc .)
- Assembly A is being linked and merged with its dependencies.
- Would be interesting to be able to specify an implementation namespace for all types that will be linked in - eg. A.Implementation.

Doing so would cause all types in B.X, B.Y, C.Foo, C.Bar to go into the namespace A.Implementation with generated/obfuscated unique names. The unique-ness bit is so that type name conflicts don't arise from merging namespaces.

The motivation behind the scenario is to hide the implementation of A, and after merging/linking it is not apparent what its dependencies were.

Thoughts? Is this something that would be doable based on the assembly rewriting facilities provided by Cecil and how ILRepack works?

**Comment by PedroMGMendes** [comment]
Hi, 

Thanks for ILRepack, really helpfull.

I had this same (pratically the same) feature request and developed it. This is what i added:

/renameNameSpaces[:<namespacestorenamefile>] Renames all types (FullName) that match the regular expression by the specified value. The file <namespacestorenamefile> contains one regex per line followed by the new namespace value. Regex and new value must be separated by a tab char ['\t']. Sample line: ^(Microsoft)    Ms
 
Bit of a newbie github user, anyway can i create a pull request for this and submit my changes for approval?

Thanks.

**Comment by KirillOsenkov** [comment]
We decided not to do it:
https://github.com/gluck/il-repack/pull/268#issuecomment-1879913959
