### ISSUE TITLE
Explicitly implemented property disappears in certain scenarios

### ISSUE THREAD

**Issue by fnajera-rac-de** [gluck/il-repack#62]
There's a bug when merging a type that contains two explicitly implemented indexer properties that differ on the arguments.

These properties are named not just "Index" but "InterfaceFullName.Index". The code at ILRepack.IsIndexer() checks only for "Index" and not for strings ending with ".Index", which makes it think that one of them is a duplicated.

My fix is to change the code from:

```
        private static bool IsIndexer(PropertyDefinition prop)
        {
            if (prop.Name != "Item")
                return false;
```

to

```
        private static bool IsIndexer(PropertyDefinition prop)
        {
            if (prop.Name != "Item" && !prop.Name.EndsWith(".Item")) // cover explicitely implemented properties
                return false;
```

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/gluck/il-repack/commit/51f810dd1c319c5b4b6e1e7f6728074655425525, thanks
