### ISSUE TITLE
Consider update ILRepack to 4.0 framework

### ISSUE THREAD

**Issue by XVincentX** [gluck/il-repack#71]

**Comment by gluck** [comment]
Hi,

What's your need for a 4.0 ILRepack version ?

Thx

**Comment by XVincentX** [comment]
Time is passing, 3.5 is not installed by default on Windows 8 anymore and it may be annoying to install.

**Comment by gluck** [comment]
I was pretty sure runtime 4 and 4.5 could run 3.5 assemblies w/o issue (e.g. I can use a 3.5 DLL in a 4.0 executable), are you saying it doesn't ?

**Comment by XVincentX** [comment]
Looks like no. Windows 8 requires .NET 3.5 installed to run ILRepack.exe

**Comment by gluck** [comment]
http://msdn.microsoft.com/en-us/library/jj152935(v=vs.110).aspx

What if you add the proper app.config to allow 4.0 ?

**Comment by XVincentX** [comment]
It should work, I think. Going to try that.
