### ISSUE TITLE
ArgumentOutOfRange exception when using on Paket

### ISSUE THREAD

**Issue by forki** [gluck/il-repack#72]
I tried to update to latest ILRepack from mono, but get ArgumentOutOfRange exception.

A repro sample is at https://github.com/fsprojects/Paket/pull/555 - just run `build MergePaketTool` from command promt.

![image](https://cloud.githubusercontent.com/assets/57396/5798023/661a3f56-9fc3-11e4-8888-e35d2528078f.png)

We used 1.21.2.0 (downloaded from somewhere on the internet) and that worked fine.

**Comment by forki** [comment]
any news on that? it would be very important for F# projects to get that fixed.

**Comment by gluck** [comment]
Fixed in 1.26.0

**Comment by forki** [comment]
![working](https://cloud.githubusercontent.com/assets/57396/7444369/a2f3770e-f17f-11e4-97b9-fd5487a4829a.gif)

It seems to work. Thanks a lot.
