### ISSUE TITLE
Error while attempting to import resource file Arg_ResourceFileUnsupportedVersion

### ISSUE THREAD

**Issue by Danprot** [gluck/il-repack#73]
Error while attempting to import resource file Arg_ResourceFileUnsupportedVersion
Arg_ResourceFileUnsupportedVersion - unlocalized
found in http://referencesource.microsoft.com/#mscorlib/system/resources/resourcereader.cs 
## log:

INFO: - Importing Microsoft.TeamFoundation.Proxy.ManageTfsListInternal.resources
System.ArgumentException: Arg_ResourceFileUnsupportedVersion
   в ILRepacking.ResReader..ctor(Stream stream)
   в ILRepacking.ILRepack.FixResxResource(EmbeddedResource er)
   в ILRepacking.ILRepack.RepackResources()
   в ILRepacking.ILRepack.Repack()
   в ILRepacking.ILRepack.Main(String[] args)

**Comment by gluck** [comment]
What was the assemblies you're trying to merge ?

**Comment by NenoLoje** [comment]
**+1**, I got the same error message today. It seems that the issue occurs when trying to il-pack the Team Foundation Server Object Model.

**Steps to reproduce**
Try to il-pack the "Microsoft.TeamFoundation.Client.dll" with your project.

**Where to get "Microsoft.TeamFoundation.Client.dll"?**
- In VS 2015 you can do that by dding the Microsoft.TeamFoundation.ExtendedClient NuGet package,
- In VS 2013 you can find it in the Add Reference dialog.

**Command Line Output**
> ilrepack /target:exe /out:Foo.exe Bar.exe Microsoft.TeamFoundation.Client.dll
INFO: IL Repack - Version 2.0.5
INFO: Adding assembly for merge: Bar.exe
INFO: Adding assembly for merge: Microsoft.TeamFoundation.Client.dll
INFO: Processing references
INFO: Processing types
INFO: Merging <Module>
INFO: Merging <Module>
INFO: Processing types
INFO: Processing resources
System.ArgumentException: Arg_ResourceFileUnsupportedVersion
   bei ILRepacking.ResReader..ctor(Stream stream)
   bei ILRepacking.Steps.ResourcesRepackStep.FixResxResource(AssemblyDefinition
containingAssembly, EmbeddedResource er, List`1 resourcePrcessors, IEmbeddedReso
urceProcessor embeddedResourceProcessor)
   bei ILRepacking.Steps.ResourcesRepackStep.Perform()
   bei ILRepacking.ILRepack.Repack()
   bei ILRepacking.Application.Main(String[] args)

Let me know if you need more info.

--Neno

**Comment by lextm** [comment]
I don't even think it is legal to merge such assemblies with yours, though there can be some technical investigation to do.

**Comment by gluck** [comment]
What re-assures me is that ILSpy also crashes upon reading those resources :)
I'll try to dig further what makes them so special.

@lextm I'm no lawyer but here's the [license](http://www.microsoft.com/net/dotnet_library_license.htm), it does forbid decompilation, but I'm not sure ILMerge/ILRepack qualify as "decompilers".

**Comment by KirillOsenkov** [comment]
I've tried the latest version and it seems to be working fine.
