### ISSUE TITLE
Add Donate button

### ISSUE THREAD

**Issue by asd-and-Rizzo** [gluck/il-repack#74]
I used this tool to deliver conflicting dlls in production. Please add Donation button to make little thanks.

**Comment by asd-and-Rizzo** [comment]
If you want to avoid donation consider redirect it to some FOSS project or organization protecting freedom, or whatever. https://github.com/asd-and-Rizzo/asd-and-Rizzo.github.io/blob/master/how-to-avoid-donations.md

**Comment by gluck** [comment]
Words of usefulness are thanks enough, how about a statement like the below ?

> If you like this tool and want to express your thanks, you can contribute either time to the project (issue triage or pull-requests) or donate money to the Free Software Foundation.

**Comment by asd-and-Rizzo** [comment]
Good for readme, also may add link to fsf page.
 
Some ideas for possible features which may or may  be done during IL merge https://github.com/dotnet/roslyn/issues/98 see Componentization. Seems some of these are elaborated somewhere else.

Also would be interesting to eliminate not used code during merge into exe(may get rid of not used public cause exe is not for reference), with some definition about reflection safety.
