### ISSUE TITLE
Mono.Cecil.ResolutionException: Failed to resolve <CppImplementationDetails>

### ISSUE THREAD

**Issue by qucc** [gluck/il-repack#76]
I've tried merge Microsoft.Kinect.dll with other libs, here is the exception 
ERROR: Failed to load assembly C:\Program Files\Microsoft SDKs\Kinect\v2.0_1409\
Assemblies\Microsoft.Kinect.dll
Mono.Cecil.ResolutionException: Failed to resolve <CppImplementationDetails>.$Ar
rayType$$$BY07$$CBD

**Comment by gluck** [comment]
ILRepack can't merge assemblies that include native code (which seems to be the case for Microsoft.Kinect).
I expect ILMerge to behave the same.

**Comment by timotei** [comment]
@qucc: Do you have an example (small) project which can show this error?
Also, what ILRepack version are you using?

I've just tried a simple app (.NET 4.5) that references the Microsoft.Kinect.dll and it worked just fine, no repack errors encountered.
