### ISSUE TITLE
Is it possible to use ILRepack as a dll

### ISSUE THREAD

**Issue by forki** [gluck/il-repack#94]
Is there a sample to do programmatic repackaging? I might want to do this in Paket (as a feature)

**Comment by gluck** [comment]
ILRepack.Lib NuGet package can be used for such a purpose.
However the API has quite changed in latest version, and it's not really clear whether it should be that way (or be rollbacked).

You can see (the old API) in use in [ILRepack.MSBuild.Task](https://github.com/peters/ILRepack.MSBuild.Task/blob/master/src/msbuild/ILRepack.cs) project, but it's not usable with the latest version.

**Comment by forki** [comment]
I'm not afraid of breaking APIs.
Just want to evaluate what you think about such usage.

2015-05-20 15:21 GMT+02:00 Francois Valdy <notifications@github.com>:

**Comment by gluck** [comment]
There's a package for that and it works (used to), I don't intend to get rid of it (pretty sound/valid use case).

**Comment by forki** [comment]
cool. Thanks
