### ISSUE TITLE
Is it possible to retrieve AssemblyAttributes with ILRepack?

### ISSUE THREAD

**Issue by forki** [gluck/il-repack#95]
https://github.com/fsprojects/Paket/issues/827

we struggle to retrieve CustomAttributes with reflection and all the assembly loading is crashing and locking files,...

I'm looking for a sane alternative.

**Comment by gluck** [comment]
ILRepack simply uses Mono.Cecil under the hood, AFAICT you should use Cecil too instead of System.Reflection to avoid loading up the assemblies "for real".
But you probably already know that, so I may have missed the point of your question :)

**Comment by forki** [comment]
ok. let's rephrase:

I assume we will take a dependency on ILRepack very soon. Since you depend
on Mono.Cecil I wonder if the API is still accessible in ILRepack.

2015-05-20 15:35 GMT+02:00 Francois Valdy <notifications@github.com>:

**Comment by gluck** [comment]
Nope, Cecil version (custom build) is internalized in ILRepack.
You can use Cecil (any version) on your own though, it won't affect ILRepack.

You'll end up with duplicate Cecil types in your runtime, but I'm not sure you need to be concerned about that.

**Comment by forki** [comment]
> You'll end up with duplicate Cecil types in your runtime, but I'm not sure you need to be concerned about that.

Only concern is my dll file size.

**Comment by gluck** [comment]
So that ~400k you could get rid of by not-internalizing-cecil in ILRepack and sharing the dependency.
Definitely doable, if you think it's worth it.
