### ISSUE TITLE
Merging System.Reactive.Core and System.Reactive.Interfaces adds mscrolib

### ISSUE THREAD

**Issue by biz0n** [gluck/il-repack#97]
Mscorlib doesnt exist in references of any of these libs.

The only type for which mscorlib is added is DebuggableAttribute which SHOULD be resolved from System.Runtime.dll in PCL.

**Comment by gluck** [comment]
That's the work of cecil ([here](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/TypeSystem.cs#L108)), whichs hooks all primitive types to mscorlib and adds the assembly reference (though it's unneeded).
If you ILDASM the resulting assembly (with tokens), you'll see thsat the mscorlib assemblyref is never actually used.
A bit troubling, but I can't really tell if it has any impact, do you think there's one ?
