### ISSUE TITLE
Passing framework path with spaces doesn't work

### ISSUE THREAD

**Issue by biz0n** [gluck/il-repack#98]
Seems args are parsed incorrectly. 
Quotes don't work too

/pause /targetplatform:v4,"%programfiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\" /out:c:\tmp\winTest.dll c:\tmp\System.Reactive.Core.dll c:\tmp\System.Reactive.Interfaces.dll

EnvVariables are not expanded, but this is okay :)

**Comment by gluck** [comment]
The entire arg needs to be quoted (along with `/targetplatform:v4,`) not just the fwk path.
AFAIK this is standard argument parsing, but I may be wrong on that, why did you expect it to behave this way ?
