### ISSUE TITLE
Unable to merge microsoft.bcl assemblies

### ISSUE THREAD

**Issue by steveellis** [gluck/il-repack#99]
Microsoft has made three assemblies available to support async await and HttpClient on v4. These are:
microsoft.bcl
microsoft.bcl.async
microsoft.net.http

I'm unable to successfully merge a project when these assemblies are included.

The exception I get is:

1>  Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
1>     at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
1>     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
1>     at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
1>     at Mono.Cecil.TypeReference.Resolve()
1>     at ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
1>     at ILRepacking.ReferenceFixator.FixReferences(MethodDefinition meth)
1>     at ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
1>     at ILRepacking.ILRepack.Repack()
1>     at ILRepacking.Application.Main(String[] args)

I made a test project in VS to demonstrate the issue which is available here:

https://backup.filesanywhere.com/fs/v.aspx?v=8d6a648d5a607077af6e

Any help would be greatly appreciated!

Steve

**Comment by gluck** [comment]
Duplicate #58
Will be fixed in 2.0, though I think you can work around it if you somehow force ilrepack to execute with v4 clr.
